//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:00:21 PM CET 
//


package org.kit.scufl.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * An activity is the link between a processor and the
 * 				actual service. Typical activities can be the WSDL activity that
 * 				knows how to communicate with WSDL-services, the Beanshell activity
 * 				that knows how to locally execute a Beanshell script, or a Dataflow
 * 				activity that knows how to execute a nested dataflow. (Typically
 * 				included as another dataflow element within this Workflow
 * 				description).
 * 			
 * 
 * <p>Java class for Activity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Activity">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="raven" type="{http://taverna.sf.net/2008/xml/t2flow}Raven" minOccurs="0"/>
 *         &lt;element name="class" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="inputMap" type="{http://taverna.sf.net/2008/xml/t2flow}Map"/>
 *         &lt;element name="outputMap" type="{http://taverna.sf.net/2008/xml/t2flow}Map"/>
 *         &lt;element name="configBean" type="{http://taverna.sf.net/2008/xml/t2flow}ConfigBean"/>
 *         &lt;element name="annotations" type="{http://taverna.sf.net/2008/xml/t2flow}Annotations" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Activity", propOrder = {
    "raven",
    "clazz",
    "inputMap",
    "outputMap",
    "configBean",
    "annotations"
})
public class Activity {

    @XmlElement(namespace = "http://taverna.sf.net/2008/xml/t2flow")
    protected Raven raven;
    @XmlElement(name = "class", namespace = "http://taverna.sf.net/2008/xml/t2flow", required = true)
    protected String clazz;
    @XmlElement(namespace = "http://taverna.sf.net/2008/xml/t2flow", required = true)
    protected Map inputMap;
    @XmlElement(namespace = "http://taverna.sf.net/2008/xml/t2flow", required = true)
    protected Map outputMap;
    @XmlElement(namespace = "http://taverna.sf.net/2008/xml/t2flow", required = true)
    protected ConfigBean configBean;
    @XmlElement(namespace = "http://taverna.sf.net/2008/xml/t2flow")
    protected Annotations annotations;

    /**
     * Gets the value of the raven property.
     * 
     * @return
     *     possible object is
     *     {@link Raven }
     *     
     */
    public Raven getRaven() {
        return raven;
    }

    /**
     * Sets the value of the raven property.
     * 
     * @param value
     *     allowed object is
     *     {@link Raven }
     *     
     */
    public void setRaven(Raven value) {
        this.raven = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClazz(String value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the inputMap property.
     * 
     * @return
     *     possible object is
     *     {@link Map }
     *     
     */
    public Map getInputMap() {
        return inputMap;
    }

    /**
     * Sets the value of the inputMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link Map }
     *     
     */
    public void setInputMap(Map value) {
        this.inputMap = value;
    }

    /**
     * Gets the value of the outputMap property.
     * 
     * @return
     *     possible object is
     *     {@link Map }
     *     
     */
    public Map getOutputMap() {
        return outputMap;
    }

    /**
     * Sets the value of the outputMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link Map }
     *     
     */
    public void setOutputMap(Map value) {
        this.outputMap = value;
    }

    /**
     * Gets the value of the configBean property.
     * 
     * @return
     *     possible object is
     *     {@link ConfigBean }
     *     
     */
    public ConfigBean getConfigBean() {
        return configBean;
    }

    /**
     * Sets the value of the configBean property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfigBean }
     *     
     */
    public void setConfigBean(ConfigBean value) {
        this.configBean = value;
    }

    /**
     * Gets the value of the annotations property.
     * 
     * @return
     *     possible object is
     *     {@link Annotations }
     *     
     */
    public Annotations getAnnotations() {
        return annotations;
    }

    /**
     * Sets the value of the annotations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Annotations }
     *     
     */
    public void setAnnotations(Annotations value) {
        this.annotations = value;
    }

}
