//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:00:21 PM CET 
//


package org.kit.scufl.api;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ArtifactDependencies complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArtifactDependencies">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="net.sf.taverna.raven.repository.BasicArtifact" type="{http://taverna.sf.net/2008/xml/t2activities}BasicArtifact" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArtifactDependencies", namespace = "http://taverna.sf.net/2008/xml/t2activities", propOrder = {
    "netSfTavernaRavenRepositoryBasicArtifact"
})
public class ArtifactDependencies {

    @XmlElement(name = "net.sf.taverna.raven.repository.BasicArtifact")
    protected List<BasicArtifact> netSfTavernaRavenRepositoryBasicArtifact;

    /**
     * Gets the value of the netSfTavernaRavenRepositoryBasicArtifact property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the netSfTavernaRavenRepositoryBasicArtifact property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNetSfTavernaRavenRepositoryBasicArtifact().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BasicArtifact }
     * 
     * 
     */
    public List<BasicArtifact> getNetSfTavernaRavenRepositoryBasicArtifact() {
        if (netSfTavernaRavenRepositoryBasicArtifact == null) {
            netSfTavernaRavenRepositoryBasicArtifact = new ArrayList<BasicArtifact>();
        }
        return this.netSfTavernaRavenRepositoryBasicArtifact;
    }

}
