//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:00:21 PM CET 
//


package org.kit.scufl.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Configuration for the Beanshell activity.
 * 			
 * 
 * <p>Java class for BeanshellConfig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BeanshellConfig">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="script" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dependencies" type="{http://taverna.sf.net/2008/xml/t2activities}Dependencies"/>
 *         &lt;element name="classLoaderSharing" type="{http://taverna.sf.net/2008/xml/t2activities}ClassLoaderSharing"/>
 *         &lt;element name="localDependencies" type="{http://taverna.sf.net/2008/xml/t2activities}LocalDependencies"/>
 *         &lt;element name="artifactDependencies" type="{http://taverna.sf.net/2008/xml/t2activities}ArtifactDependencies"/>
 *         &lt;element name="inputs" type="{http://taverna.sf.net/2008/xml/t2activities}ActivityInputPorts"/>
 *         &lt;element name="outputs" type="{http://taverna.sf.net/2008/xml/t2activities}ActivityOutputPorts"/>
 *         &lt;element name="localworkerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BeanshellConfig", namespace = "http://taverna.sf.net/2008/xml/t2activities", propOrder = {

})
public class BeanshellConfig {

    @XmlElement(required = true)
    protected String script;
    @XmlElement(required = true)
    protected Dependencies dependencies;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected ClassLoaderSharing classLoaderSharing;
    @XmlElement(required = true)
    protected LocalDependencies localDependencies;
    @XmlElement(required = true)
    protected ArtifactDependencies artifactDependencies;
    @XmlElement(required = true)
    protected ActivityInputPorts inputs;
    @XmlElement(required = true)
    protected ActivityOutputPorts outputs;
    protected String localworkerName;

    /**
     * Gets the value of the script property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScript() {
        return script;
    }

    /**
     * Sets the value of the script property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScript(String value) {
        this.script = value;
    }

    /**
     * Gets the value of the dependencies property.
     * 
     * @return
     *     possible object is
     *     {@link Dependencies }
     *     
     */
    public Dependencies getDependencies() {
        return dependencies;
    }

    /**
     * Sets the value of the dependencies property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dependencies }
     *     
     */
    public void setDependencies(Dependencies value) {
        this.dependencies = value;
    }

    /**
     * Gets the value of the classLoaderSharing property.
     * 
     * @return
     *     possible object is
     *     {@link ClassLoaderSharing }
     *     
     */
    public ClassLoaderSharing getClassLoaderSharing() {
        return classLoaderSharing;
    }

    /**
     * Sets the value of the classLoaderSharing property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassLoaderSharing }
     *     
     */
    public void setClassLoaderSharing(ClassLoaderSharing value) {
        this.classLoaderSharing = value;
    }

    /**
     * Gets the value of the localDependencies property.
     * 
     * @return
     *     possible object is
     *     {@link LocalDependencies }
     *     
     */
    public LocalDependencies getLocalDependencies() {
        return localDependencies;
    }

    /**
     * Sets the value of the localDependencies property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocalDependencies }
     *     
     */
    public void setLocalDependencies(LocalDependencies value) {
        this.localDependencies = value;
    }

    /**
     * Gets the value of the artifactDependencies property.
     * 
     * @return
     *     possible object is
     *     {@link ArtifactDependencies }
     *     
     */
    public ArtifactDependencies getArtifactDependencies() {
        return artifactDependencies;
    }

    /**
     * Sets the value of the artifactDependencies property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArtifactDependencies }
     *     
     */
    public void setArtifactDependencies(ArtifactDependencies value) {
        this.artifactDependencies = value;
    }

    /**
     * Gets the value of the inputs property.
     * 
     * @return
     *     possible object is
     *     {@link ActivityInputPorts }
     *     
     */
    public ActivityInputPorts getInputs() {
        return inputs;
    }

    /**
     * Sets the value of the inputs property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActivityInputPorts }
     *     
     */
    public void setInputs(ActivityInputPorts value) {
        this.inputs = value;
    }

    /**
     * Gets the value of the outputs property.
     * 
     * @return
     *     possible object is
     *     {@link ActivityOutputPorts }
     *     
     */
    public ActivityOutputPorts getOutputs() {
        return outputs;
    }

    /**
     * Sets the value of the outputs property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActivityOutputPorts }
     *     
     */
    public void setOutputs(ActivityOutputPorts value) {
        this.outputs = value;
    }

    /**
     * Gets the value of the localworkerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalworkerName() {
        return localworkerName;
    }

    /**
     * Sets the value of the localworkerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalworkerName(String value) {
        this.localworkerName = value;
    }

}
