//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:00:21 PM CET 
//


package org.kit.scufl.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BioMobyConfig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BioMobyConfig">
 *   &lt;complexContent>
 *     &lt;extension base="{http://taverna.sf.net/2008/xml/t2activities}BioMobyObjectConfig">
 *       &lt;sequence>
 *         &lt;element name="category" type="{http://taverna.sf.net/2008/xml/t2activities}BioMobyCategory"/>
 *         &lt;element name="serviceType" type="{http://taverna.sf.net/2008/xml/t2activities}BioMobyServiceType"/>
 *         &lt;element name="secondaries" type="{http://taverna.sf.net/2008/xml/t2activities}BioMobySecondaries"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BioMobyConfig", namespace = "http://taverna.sf.net/2008/xml/t2activities", propOrder = {
    "category",
    "serviceType",
    "secondaries"
})
public class BioMobyConfig
    extends BioMobyObjectConfig
{

    @XmlElement(required = true)
    protected BioMobyCategory category;
    @XmlElement(required = true)
    protected BioMobyServiceType serviceType;
    @XmlElement(required = true)
    protected BioMobySecondaries secondaries;

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link BioMobyCategory }
     *     
     */
    public BioMobyCategory getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link BioMobyCategory }
     *     
     */
    public void setCategory(BioMobyCategory value) {
        this.category = value;
    }

    /**
     * Gets the value of the serviceType property.
     * 
     * @return
     *     possible object is
     *     {@link BioMobyServiceType }
     *     
     */
    public BioMobyServiceType getServiceType() {
        return serviceType;
    }

    /**
     * Sets the value of the serviceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BioMobyServiceType }
     *     
     */
    public void setServiceType(BioMobyServiceType value) {
        this.serviceType = value;
    }

    /**
     * Gets the value of the secondaries property.
     * 
     * @return
     *     possible object is
     *     {@link BioMobySecondaries }
     *     
     */
    public BioMobySecondaries getSecondaries() {
        return secondaries;
    }

    /**
     * Sets the value of the secondaries property.
     * 
     * @param value
     *     allowed object is
     *     {@link BioMobySecondaries }
     *     
     */
    public void setSecondaries(BioMobySecondaries value) {
        this.secondaries = value;
    }

}
