//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:00:21 PM CET 
//


package org.kit.scufl.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComponentConfig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComponentConfig">
 *   &lt;complexContent>
 *     &lt;extension base="{http://taverna.sf.net/2008/xml/t2flow}AbstractConfigBean">
 *       &lt;sequence>
 *         &lt;element name="registryBase" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="familyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="componentName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="componentVersion" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComponentConfig", namespace = "", propOrder = {
    "registryBase",
    "familyName",
    "componentName",
    "componentVersion"
})
public class ComponentConfig
    extends AbstractConfigBean
{

    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String registryBase;
    @XmlElement(required = true)
    protected String familyName;
    @XmlElement(required = true)
    protected String componentName;
    protected Integer componentVersion;

    /**
     * Gets the value of the registryBase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegistryBase() {
        return registryBase;
    }

    /**
     * Sets the value of the registryBase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegistryBase(String value) {
        this.registryBase = value;
    }

    /**
     * Gets the value of the familyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFamilyName() {
        return familyName;
    }

    /**
     * Sets the value of the familyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFamilyName(String value) {
        this.familyName = value;
    }

    /**
     * Gets the value of the componentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComponentName() {
        return componentName;
    }

    /**
     * Sets the value of the componentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComponentName(String value) {
        this.componentName = value;
    }

    /**
     * Gets the value of the componentVersion property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getComponentVersion() {
        return componentVersion;
    }

    /**
     * Sets the value of the componentVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setComponentVersion(Integer value) {
        this.componentVersion = value;
    }

}
