//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:00:21 PM CET 
//


package org.kit.scufl.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A dataflow, that is a workflow that is data-driven.
 * 				When running a dataflow, data is pushed onto the inputPorts, leading
 * 				through the datalinks to the input ports of processors. The output
 * 				ports of these processors again have datalinks to other processors,
 * 				and to outputPorts, which are the results of the workflow.
 * 				Additional control links can be listed under 'conditions', and
 * 				annotations (descriptions) about the Dataflow under 'annotations'.
 * 				The "role" attribute should be "top" for the main dataflow, and
 * 				"nested" for nested dataflows. The uuid-s in "id" can be referenced
 * 				from a nested dataflow activity.
 * 			
 * 
 * <p>Java class for Dataflow complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Dataflow">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="inputPorts" type="{http://taverna.sf.net/2008/xml/t2flow}AnnotatedGranularDepthPorts"/>
 *         &lt;element name="outputPorts" type="{http://taverna.sf.net/2008/xml/t2flow}AnnotatedPorts"/>
 *         &lt;element name="processors" type="{http://taverna.sf.net/2008/xml/t2flow}Processors"/>
 *         &lt;element name="conditions" type="{http://taverna.sf.net/2008/xml/t2flow}Conditions"/>
 *         &lt;element name="datalinks" type="{http://taverna.sf.net/2008/xml/t2flow}Datalinks"/>
 *         &lt;element name="annotations" type="{http://taverna.sf.net/2008/xml/t2flow}Annotations" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://taverna.sf.net/2008/xml/t2flow}uuid" />
 *       &lt;attribute name="role" use="required" type="{http://taverna.sf.net/2008/xml/t2flow}role" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Dataflow", propOrder = {
    "name",
    "inputPorts",
    "outputPorts",
    "processors",
    "conditions",
    "datalinks",
    "annotations"
})
public class Dataflow {

    @XmlElement(namespace = "http://taverna.sf.net/2008/xml/t2flow", required = true)
    protected String name;
    @XmlElement(namespace = "http://taverna.sf.net/2008/xml/t2flow", required = true)
    protected AnnotatedGranularDepthPorts inputPorts;
    @XmlElement(namespace = "http://taverna.sf.net/2008/xml/t2flow", required = true)
    protected AnnotatedPorts outputPorts;
    @XmlElement(namespace = "http://taverna.sf.net/2008/xml/t2flow", required = true)
    protected Processors processors;
    @XmlElement(namespace = "http://taverna.sf.net/2008/xml/t2flow", required = true)
    protected Conditions conditions;
    @XmlElement(namespace = "http://taverna.sf.net/2008/xml/t2flow", required = true)
    protected Datalinks datalinks;
    @XmlElement(namespace = "http://taverna.sf.net/2008/xml/t2flow")
    protected Annotations annotations;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "role", required = true)
    protected Role role;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the inputPorts property.
     * 
     * @return
     *     possible object is
     *     {@link AnnotatedGranularDepthPorts }
     *     
     */
    public AnnotatedGranularDepthPorts getInputPorts() {
        return inputPorts;
    }

    /**
     * Sets the value of the inputPorts property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnnotatedGranularDepthPorts }
     *     
     */
    public void setInputPorts(AnnotatedGranularDepthPorts value) {
        this.inputPorts = value;
    }

    /**
     * Gets the value of the outputPorts property.
     * 
     * @return
     *     possible object is
     *     {@link AnnotatedPorts }
     *     
     */
    public AnnotatedPorts getOutputPorts() {
        return outputPorts;
    }

    /**
     * Sets the value of the outputPorts property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnnotatedPorts }
     *     
     */
    public void setOutputPorts(AnnotatedPorts value) {
        this.outputPorts = value;
    }

    /**
     * Gets the value of the processors property.
     * 
     * @return
     *     possible object is
     *     {@link Processors }
     *     
     */
    public Processors getProcessors() {
        return processors;
    }

    /**
     * Sets the value of the processors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Processors }
     *     
     */
    public void setProcessors(Processors value) {
        this.processors = value;
    }

    /**
     * Gets the value of the conditions property.
     * 
     * @return
     *     possible object is
     *     {@link Conditions }
     *     
     */
    public Conditions getConditions() {
        return conditions;
    }

    /**
     * Sets the value of the conditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Conditions }
     *     
     */
    public void setConditions(Conditions value) {
        this.conditions = value;
    }

    /**
     * Gets the value of the datalinks property.
     * 
     * @return
     *     possible object is
     *     {@link Datalinks }
     *     
     */
    public Datalinks getDatalinks() {
        return datalinks;
    }

    /**
     * Sets the value of the datalinks property.
     * 
     * @param value
     *     allowed object is
     *     {@link Datalinks }
     *     
     */
    public void setDatalinks(Datalinks value) {
        this.datalinks = value;
    }

    /**
     * Gets the value of the annotations property.
     * 
     * @return
     *     possible object is
     *     {@link Annotations }
     *     
     */
    public Annotations getAnnotations() {
        return annotations;
    }

    /**
     * Sets the value of the annotations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Annotations }
     *     
     */
    public void setAnnotations(Annotations value) {
        this.annotations = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link Role }
     *     
     */
    public Role getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link Role }
     *     
     */
    public void setRole(Role value) {
        this.role = value;
    }

}
