//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:00:21 PM CET 
//


package org.kit.scufl.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A link between two dataflow units, from source to
 * 				link.
 * 			
 * 
 * <p>Java class for DataLink complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataLink">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sink" type="{http://taverna.sf.net/2008/xml/t2flow}Link"/>
 *         &lt;element name="source" type="{http://taverna.sf.net/2008/xml/t2flow}Link"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataLink", propOrder = {
    "sink",
    "source"
})
public class DataLink {

    @XmlElement(namespace = "http://taverna.sf.net/2008/xml/t2flow", required = true)
    protected Link sink;
    @XmlElement(namespace = "http://taverna.sf.net/2008/xml/t2flow", required = true)
    protected Link source;

    /**
     * Gets the value of the sink property.
     * 
     * @return
     *     possible object is
     *     {@link Link }
     *     
     */
    public Link getSink() {
        return sink;
    }

    /**
     * Sets the value of the sink property.
     * 
     * @param value
     *     allowed object is
     *     {@link Link }
     *     
     */
    public void setSink(Link value) {
        this.sink = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link Link }
     *     
     */
    public Link getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link Link }
     *     
     */
    public void setSource(Link value) {
        this.source = value;
    }

}
