//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:00:21 PM CET 
//


package org.kit.scufl.api;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * List of dispatch layers. This would typically contain
 * 				at least the Invoke layer to perform the actual invocation of the
 * 				activity.
 * 			
 * 
 * <p>Java class for DispatchStack complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DispatchStack">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dispatchLayer" type="{http://taverna.sf.net/2008/xml/t2flow}DispatchLayer" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DispatchStack", propOrder = {
    "dispatchLayer"
})
public class DispatchStack {

    @XmlElement(namespace = "http://taverna.sf.net/2008/xml/t2flow")
    protected List<DispatchLayer> dispatchLayer;

    /**
     * Gets the value of the dispatchLayer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dispatchLayer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDispatchLayer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DispatchLayer }
     * 
     * 
     */
    public List<DispatchLayer> getDispatchLayer() {
        if (dispatchLayer == null) {
            dispatchLayer = new ArrayList<DispatchLayer>();
        }
        return this.dispatchLayer;
    }

}
