//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:00:21 PM CET 
//


package org.kit.scufl.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Entry complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Entry">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="string" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;choice>
 *           &lt;element name="de.uni__luebeck.inb.knowarc.usecases.ScriptInputUser" type="{}ScriptInputUser"/>
 *           &lt;element name="de.uni__luebeck.inb.knowarc.usecases.ScriptOutput" type="{}ScriptOutput"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Entry", namespace = "", propOrder = {
    "string",
    "deUniLuebeckInbKnowarcUsecasesScriptInputUser",
    "deUniLuebeckInbKnowarcUsecasesScriptOutput"
})
public class Entry {

    @XmlElement(required = true)
    protected String string;
    @XmlElement(name = "de.uni__luebeck.inb.knowarc.usecases.ScriptInputUser")
    protected ScriptInputUser deUniLuebeckInbKnowarcUsecasesScriptInputUser;
    @XmlElement(name = "de.uni__luebeck.inb.knowarc.usecases.ScriptOutput")
    protected ScriptOutput deUniLuebeckInbKnowarcUsecasesScriptOutput;

    /**
     * Gets the value of the string property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getString() {
        return string;
    }

    /**
     * Sets the value of the string property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setString(String value) {
        this.string = value;
    }

    /**
     * Gets the value of the deUniLuebeckInbKnowarcUsecasesScriptInputUser property.
     * 
     * @return
     *     possible object is
     *     {@link ScriptInputUser }
     *     
     */
    public ScriptInputUser getDeUniLuebeckInbKnowarcUsecasesScriptInputUser() {
        return deUniLuebeckInbKnowarcUsecasesScriptInputUser;
    }

    /**
     * Sets the value of the deUniLuebeckInbKnowarcUsecasesScriptInputUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScriptInputUser }
     *     
     */
    public void setDeUniLuebeckInbKnowarcUsecasesScriptInputUser(ScriptInputUser value) {
        this.deUniLuebeckInbKnowarcUsecasesScriptInputUser = value;
    }

    /**
     * Gets the value of the deUniLuebeckInbKnowarcUsecasesScriptOutput property.
     * 
     * @return
     *     possible object is
     *     {@link ScriptOutput }
     *     
     */
    public ScriptOutput getDeUniLuebeckInbKnowarcUsecasesScriptOutput() {
        return deUniLuebeckInbKnowarcUsecasesScriptOutput;
    }

    /**
     * Sets the value of the deUniLuebeckInbKnowarcUsecasesScriptOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScriptOutput }
     *     
     */
    public void setDeUniLuebeckInbKnowarcUsecasesScriptOutput(ScriptOutput value) {
        this.deUniLuebeckInbKnowarcUsecasesScriptOutput = value;
    }

}
