//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:00:21 PM CET 
//


package org.kit.scufl.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExternalToolConfig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExternalToolConfig">
 *   &lt;complexContent>
 *     &lt;extension base="{http://taverna.sf.net/2008/xml/t2flow}AbstractConfigBean">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element name="mechanismType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *             &lt;element name="mechanismName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *             &lt;element name="mechanismXML" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;/sequence>
 *           &lt;element name="group" type="{}Group"/>
 *         &lt;/choice>
 *         &lt;element name="repositoryUrl" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="externaltoolid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="useCaseDescription" type="{}UsecaseDescription"/>
 *         &lt;element name="edited" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExternalToolConfig", namespace = "", propOrder = {
    "mechanismType",
    "mechanismName",
    "mechanismXML",
    "group",
    "repositoryUrl",
    "externaltoolid",
    "useCaseDescription",
    "edited"
})
public class ExternalToolConfig
    extends AbstractConfigBean
{

    protected String mechanismType;
    protected String mechanismName;
    protected String mechanismXML;
    protected Group group;
    @XmlSchemaType(name = "anyURI")
    protected String repositoryUrl;
    @XmlElement(required = true)
    protected String externaltoolid;
    @XmlElement(required = true)
    protected UsecaseDescription useCaseDescription;
    protected boolean edited;

    /**
     * Gets the value of the mechanismType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMechanismType() {
        return mechanismType;
    }

    /**
     * Sets the value of the mechanismType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMechanismType(String value) {
        this.mechanismType = value;
    }

    /**
     * Gets the value of the mechanismName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMechanismName() {
        return mechanismName;
    }

    /**
     * Sets the value of the mechanismName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMechanismName(String value) {
        this.mechanismName = value;
    }

    /**
     * Gets the value of the mechanismXML property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMechanismXML() {
        return mechanismXML;
    }

    /**
     * Sets the value of the mechanismXML property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMechanismXML(String value) {
        this.mechanismXML = value;
    }

    /**
     * Gets the value of the group property.
     * 
     * @return
     *     possible object is
     *     {@link Group }
     *     
     */
    public Group getGroup() {
        return group;
    }

    /**
     * Sets the value of the group property.
     * 
     * @param value
     *     allowed object is
     *     {@link Group }
     *     
     */
    public void setGroup(Group value) {
        this.group = value;
    }

    /**
     * Gets the value of the repositoryUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepositoryUrl() {
        return repositoryUrl;
    }

    /**
     * Sets the value of the repositoryUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepositoryUrl(String value) {
        this.repositoryUrl = value;
    }

    /**
     * Gets the value of the externaltoolid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternaltoolid() {
        return externaltoolid;
    }

    /**
     * Sets the value of the externaltoolid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternaltoolid(String value) {
        this.externaltoolid = value;
    }

    /**
     * Gets the value of the useCaseDescription property.
     * 
     * @return
     *     possible object is
     *     {@link UsecaseDescription }
     *     
     */
    public UsecaseDescription getUseCaseDescription() {
        return useCaseDescription;
    }

    /**
     * Sets the value of the useCaseDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsecaseDescription }
     *     
     */
    public void setUseCaseDescription(UsecaseDescription value) {
        this.useCaseDescription = value;
    }

    /**
     * Gets the value of the edited property.
     * 
     */
    public boolean isEdited() {
        return edited;
    }

    /**
     * Sets the value of the edited property.
     * 
     */
    public void setEdited(boolean value) {
        this.edited = value;
    }

}
