//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:00:21 PM CET 
//


package org.kit.scufl.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InteractionConfig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InteractionConfig">
 *   &lt;complexContent>
 *     &lt;extension base="{http://taverna.sf.net/2008/xml/t2flow}AbstractConfigBean">
 *       &lt;sequence>
 *         &lt;element name="inputs" type="{http://taverna.sf.net/2008/xml/t2activities}ActivityInputPorts"/>
 *         &lt;element name="outputs" type="{http://taverna.sf.net/2008/xml/t2activities}ActivityOutputPorts"/>
 *         &lt;element name="presentationOrigin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="interactionActivityType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="progressNotification" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InteractionConfig", namespace = "", propOrder = {
    "inputs",
    "outputs",
    "presentationOrigin",
    "interactionActivityType",
    "progressNotification"
})
public class InteractionConfig
    extends AbstractConfigBean
{

    @XmlElement(required = true)
    protected ActivityInputPorts inputs;
    @XmlElement(required = true)
    protected ActivityOutputPorts outputs;
    protected String presentationOrigin;
    protected String interactionActivityType;
    protected Boolean progressNotification;

    /**
     * Gets the value of the inputs property.
     * 
     * @return
     *     possible object is
     *     {@link ActivityInputPorts }
     *     
     */
    public ActivityInputPorts getInputs() {
        return inputs;
    }

    /**
     * Sets the value of the inputs property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActivityInputPorts }
     *     
     */
    public void setInputs(ActivityInputPorts value) {
        this.inputs = value;
    }

    /**
     * Gets the value of the outputs property.
     * 
     * @return
     *     possible object is
     *     {@link ActivityOutputPorts }
     *     
     */
    public ActivityOutputPorts getOutputs() {
        return outputs;
    }

    /**
     * Sets the value of the outputs property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActivityOutputPorts }
     *     
     */
    public void setOutputs(ActivityOutputPorts value) {
        this.outputs = value;
    }

    /**
     * Gets the value of the presentationOrigin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPresentationOrigin() {
        return presentationOrigin;
    }

    /**
     * Sets the value of the presentationOrigin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPresentationOrigin(String value) {
        this.presentationOrigin = value;
    }

    /**
     * Gets the value of the interactionActivityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInteractionActivityType() {
        return interactionActivityType;
    }

    /**
     * Sets the value of the interactionActivityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInteractionActivityType(String value) {
        this.interactionActivityType = value;
    }

    /**
     * Gets the value of the progressNotification property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isProgressNotification() {
        return progressNotification;
    }

    /**
     * Sets the value of the progressNotification property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setProgressNotification(Boolean value) {
        this.progressNotification = value;
    }

}
