//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:00:21 PM CET 
//


package org.kit.scufl.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * One end of the links in the Datalink. A link goes
 * 				from/to a port, either a dataflow port or a processor port. If the
 * 				type is "dataflow", then the "processor" element must not be
 * 				present, and the port defines a dataflow input (if this link is a
 * 				source) or output port (if this link is a sink). The must not be
 * 				more than one DataLink with a sink to the same dataflow output port.
 * 				If the type is "processor", then the "processor" element must be
 * 				present, and name a processor in the same dataflow. The port must
 * 				name a defined processor input port (if this link is a sink) or
 * 				processor output port (if this link is a source). There must not be
 * 				more than one DataLink with a sink to the same processor input port.
 * 				If the type is "merge", this link must be used as a source (merge
 * 				can't be used with a sink), and is similar to the type of
 * 				"processor", except that more than one link to the processor is
 * 				allowed. A "merge" element will be inserted in front of the defined
 * 				processor input port, and the incoming links will be added to the
 * 				merge in the order they have been defined in the dataflow.
 * 			
 * 
 * <p>Java class for Link complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Link">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="processor" type="{http://taverna.sf.net/2008/xml/t2flow}ProcessorName" minOccurs="0"/>
 *         &lt;element name="port" type="{http://taverna.sf.net/2008/xml/t2flow}PortName"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" use="required" type="{http://taverna.sf.net/2008/xml/t2flow}LinkType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Link", propOrder = {
    "processor",
    "port"
})
public class Link {

    @XmlElement(namespace = "http://taverna.sf.net/2008/xml/t2flow")
    protected String processor;
    @XmlElement(namespace = "http://taverna.sf.net/2008/xml/t2flow", required = true)
    protected String port;
    @XmlAttribute(name = "type", required = true)
    protected LinkType type;

    /**
     * Gets the value of the processor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessor() {
        return processor;
    }

    /**
     * Sets the value of the processor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessor(String value) {
        this.processor = value;
    }

    /**
     * Gets the value of the port property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPort() {
        return port;
    }

    /**
     * Sets the value of the port property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPort(String value) {
        this.port = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link LinkType }
     *     
     */
    public LinkType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkType }
     *     
     */
    public void setType(LinkType value) {
        this.type = value;
    }

}
