//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:00:21 PM CET 
//


package org.kit.scufl.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Configuration of the loop layer,
 * 				which can call an activity again on a given condition. The outputs
 * 				of the activity in the processor that has this layer in it's
 * 				dispatch stack will be passed to a special conditional activity,
 * 				described by conditionXML. This conditional activity will determine
 * 				if the main activity is to be called again, by returning "true" or
 * 				"false" on it's "loop" output port. If this is the case, the
 * 				original job will be sent down again in the dispatch stack, possibly
 * 				with any modified input parameters (if other output ports from the
 * 				conditional activity matches the original input port names).
 * 			
 * 
 * <p>Java class for LoopConfig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LoopConfig">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="conditionXML" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="runFirst" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="properties" type="{http://taverna.sf.net/2008/xml/t2layers}Properties"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LoopConfig", namespace = "http://taverna.sf.net/2008/xml/t2layers", propOrder = {
    "conditionXML",
    "runFirst",
    "properties"
})
public class LoopConfig {

    @XmlElement(required = true)
    protected String conditionXML;
    protected boolean runFirst;
    @XmlElement(required = true)
    protected Properties properties;

    /**
     * Gets the value of the conditionXML property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConditionXML() {
        return conditionXML;
    }

    /**
     * Sets the value of the conditionXML property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConditionXML(String value) {
        this.conditionXML = value;
    }

    /**
     * Gets the value of the runFirst property.
     * 
     */
    public boolean isRunFirst() {
        return runFirst;
    }

    /**
     * Sets the value of the runFirst property.
     * 
     */
    public void setRunFirst(boolean value) {
        this.runFirst = value;
    }

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link Properties }
     *     
     */
    public Properties getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link Properties }
     *     
     */
    public void setProperties(Properties value) {
        this.properties = value;
    }

}
