//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:00:21 PM CET 
//


package org.kit.scufl.api;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.kit.scufl.api package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _NetSfTavernaT2ActivitiesExternaltoolExternalToolActivityConfigurationBean_QNAME = new QName("", "net.sf.taverna.t2.activities.externaltool.ExternalToolActivityConfigurationBean");
    private final static QName _NetSfTavernaT2ActivitiesInteractionInteractionActivityConfigurationBean_QNAME = new QName("", "net.sf.taverna.t2.activities.interaction.InteractionActivityConfigurationBean");
    private final static QName _Workflow_QNAME = new QName("http://taverna.sf.net/2008/xml/t2flow", "workflow");
    private final static QName _NetSfTavernaT2ActivitiesUsecaseUseCaseActivityConfigurationBean_QNAME = new QName("", "net.sf.taverna.t2.activities.usecase.UseCaseActivityConfigurationBean");
    private final static QName _NetSfTavernaT2ComponentComponentActivityConfigurationBean_QNAME = new QName("", "net.sf.taverna.t2.component.ComponentActivityConfigurationBean");
    private final static QName _NetSfTavernaT2ActivitiesRestRESTActivityConfigurationBean_QNAME = new QName("", "net.sf.taverna.t2.activities.rest.RESTActivityConfigurationBean");
    private final static QName _AbstractConfigBean_QNAME = new QName("http://taverna.sf.net/2008/xml/t2flow", "abstractConfigBean");
    private final static QName _ActivityPortDefinitionBeanAllowsLiteralValues_QNAME = new QName("", "allowsLiteralValues");
    private final static QName _ActivityPortDefinitionBeanGranularDepth_QNAME = new QName("", "granularDepth");
    private final static QName _ActivityPortDefinitionBeanMimeTypes_QNAME = new QName("", "mimeTypes");
    private final static QName _ActivityPortDefinitionBeanDepth_QNAME = new QName("", "depth");
    private final static QName _ActivityPortDefinitionBeanTranslatedElementType_QNAME = new QName("", "translatedElementType");
    private final static QName _ActivityPortDefinitionBeanHandledReferenceSchemes_QNAME = new QName("", "handledReferenceSchemes");
    private final static QName _ActivityPortDefinitionBeanName_QNAME = new QName("", "name");
    private final static QName _AnnotationsAnnotationChain22_QNAME = new QName("http://taverna.sf.net/2008/xml/t2flow", "annotation_chain_2_2");
    private final static QName _AnnotationsAnnotationChain_QNAME = new QName("http://taverna.sf.net/2008/xml/t2flow", "annotation_chain");
    private final static QName _HTTPHeadersListString_QNAME = new QName("", "string");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.kit.scufl.api
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ActivityPortDefinitionBean }
     * 
     */
    public ActivityPortDefinitionBean createActivityPortDefinitionBean() {
        return new ActivityPortDefinitionBean();
    }

    /**
     * Create an instance of {@link RShellSymanticType }
     * 
     */
    public RShellSymanticType createRShellSymanticType() {
        return new RShellSymanticType();
    }

    /**
     * Create an instance of {@link RShellSymanticType.RShellPortSymanticTypeBean }
     * 
     */
    public RShellSymanticType.RShellPortSymanticTypeBean createRShellSymanticTypeRShellPortSymanticTypeBean() {
        return new RShellSymanticType.RShellPortSymanticTypeBean();
    }

    /**
     * Create an instance of {@link BioMartConfig }
     * 
     */
    public BioMartConfig createBioMartConfig() {
        return new BioMartConfig();
    }

    /**
     * Create an instance of {@link AnnotationAssertionImpl }
     * 
     */
    public AnnotationAssertionImpl createAnnotationAssertionImpl() {
        return new AnnotationAssertionImpl();
    }

    /**
     * Create an instance of {@link AnnotationChain }
     * 
     */
    public AnnotationChain createAnnotationChain() {
        return new AnnotationChain();
    }

    /**
     * Create an instance of {@link ActivityInputs }
     * 
     */
    public ActivityInputs createActivityInputs() {
        return new ActivityInputs();
    }

    /**
     * Create an instance of {@link ScriptInputStatic }
     * 
     */
    public ScriptInputStatic createScriptInputStatic() {
        return new ScriptInputStatic();
    }

    /**
     * Create an instance of {@link HTTPHeaders }
     * 
     */
    public HTTPHeaders createHTTPHeaders() {
        return new HTTPHeaders();
    }

    /**
     * Create an instance of {@link ExternalToolConfig }
     * 
     */
    public ExternalToolConfig createExternalToolConfig() {
        return new ExternalToolConfig();
    }

    /**
     * Create an instance of {@link AbstractConfigBean }
     * 
     */
    public AbstractConfigBean createAbstractConfigBean() {
        return new AbstractConfigBean();
    }

    /**
     * Create an instance of {@link InteractionConfig }
     * 
     */
    public InteractionConfig createInteractionConfig() {
        return new InteractionConfig();
    }

    /**
     * Create an instance of {@link UsecaseConfig }
     * 
     */
    public UsecaseConfig createUsecaseConfig() {
        return new UsecaseConfig();
    }

    /**
     * Create an instance of {@link ComponentConfig }
     * 
     */
    public ComponentConfig createComponentConfig() {
        return new ComponentConfig();
    }

    /**
     * Create an instance of {@link RESTConfig }
     * 
     */
    public RESTConfig createRESTConfig() {
        return new RESTConfig();
    }

    /**
     * Create an instance of {@link Group }
     * 
     */
    public Group createGroup() {
        return new Group();
    }

    /**
     * Create an instance of {@link UsecaseDescription }
     * 
     */
    public UsecaseDescription createUsecaseDescription() {
        return new UsecaseDescription();
    }

    /**
     * Create an instance of {@link EntryMap }
     * 
     */
    public EntryMap createEntryMap() {
        return new EntryMap();
    }

    /**
     * Create an instance of {@link ScriptInputUser }
     * 
     */
    public ScriptInputUser createScriptInputUser() {
        return new ScriptInputUser();
    }

    /**
     * Create an instance of {@link ReturnCodes }
     * 
     */
    public ReturnCodes createReturnCodes() {
        return new ReturnCodes();
    }

    /**
     * Create an instance of {@link ScriptOutput }
     * 
     */
    public ScriptOutput createScriptOutput() {
        return new ScriptOutput();
    }

    /**
     * Create an instance of {@link Entry }
     * 
     */
    public Entry createEntry() {
        return new Entry();
    }

    /**
     * Create an instance of {@link StaticInputs }
     * 
     */
    public StaticInputs createStaticInputs() {
        return new StaticInputs();
    }

    /**
     * Create an instance of {@link Workflow }
     * 
     */
    public Workflow createWorkflow() {
        return new Workflow();
    }

    /**
     * Create an instance of {@link GranularDepthPort }
     * 
     */
    public GranularDepthPort createGranularDepthPort() {
        return new GranularDepthPort();
    }

    /**
     * Create an instance of {@link Port }
     * 
     */
    public Port createPort() {
        return new Port();
    }

    /**
     * Create an instance of {@link IterationStrategyStack }
     * 
     */
    public IterationStrategyStack createIterationStrategyStack() {
        return new IterationStrategyStack();
    }

    /**
     * Create an instance of {@link Activity }
     * 
     */
    public Activity createActivity() {
        return new Activity();
    }

    /**
     * Create an instance of {@link Mapping }
     * 
     */
    public Mapping createMapping() {
        return new Mapping();
    }

    /**
     * Create an instance of {@link DispatchLayer }
     * 
     */
    public DispatchLayer createDispatchLayer() {
        return new DispatchLayer();
    }

    /**
     * Create an instance of {@link Conditions }
     * 
     */
    public Conditions createConditions() {
        return new Conditions();
    }

    /**
     * Create an instance of {@link Annotations }
     * 
     */
    public Annotations createAnnotations() {
        return new Annotations();
    }

    /**
     * Create an instance of {@link IterationNode }
     * 
     */
    public IterationNode createIterationNode() {
        return new IterationNode();
    }

    /**
     * Create an instance of {@link AnnotatedPorts }
     * 
     */
    public AnnotatedPorts createAnnotatedPorts() {
        return new AnnotatedPorts();
    }

    /**
     * Create an instance of {@link PortProduct }
     * 
     */
    public PortProduct createPortProduct() {
        return new PortProduct();
    }

    /**
     * Create an instance of {@link DataLink }
     * 
     */
    public DataLink createDataLink() {
        return new DataLink();
    }

    /**
     * Create an instance of {@link TopIterationNode }
     * 
     */
    public TopIterationNode createTopIterationNode() {
        return new TopIterationNode();
    }

    /**
     * Create an instance of {@link AnnotatedGranularDepthPort }
     * 
     */
    public AnnotatedGranularDepthPort createAnnotatedGranularDepthPort() {
        return new AnnotatedGranularDepthPort();
    }

    /**
     * Create an instance of {@link AnnotatedGranularDepthPorts }
     * 
     */
    public AnnotatedGranularDepthPorts createAnnotatedGranularDepthPorts() {
        return new AnnotatedGranularDepthPorts();
    }

    /**
     * Create an instance of {@link Processors }
     * 
     */
    public Processors createProcessors() {
        return new Processors();
    }

    /**
     * Create an instance of {@link Map }
     * 
     */
    public Map createMap() {
        return new Map();
    }

    /**
     * Create an instance of {@link Link }
     * 
     */
    public Link createLink() {
        return new Link();
    }

    /**
     * Create an instance of {@link AnnotationBean }
     * 
     */
    public AnnotationBean createAnnotationBean() {
        return new AnnotationBean();
    }

    /**
     * Create an instance of {@link Raven }
     * 
     */
    public Raven createRaven() {
        return new Raven();
    }

    /**
     * Create an instance of {@link Processor }
     * 
     */
    public Processor createProcessor() {
        return new Processor();
    }

    /**
     * Create an instance of {@link DepthPorts }
     * 
     */
    public DepthPorts createDepthPorts() {
        return new DepthPorts();
    }

    /**
     * Create an instance of {@link AnnotatedPort }
     * 
     */
    public AnnotatedPort createAnnotatedPort() {
        return new AnnotatedPort();
    }

    /**
     * Create an instance of {@link LastPredictedDepthPort }
     * 
     */
    public LastPredictedDepthPort createLastPredictedDepthPort() {
        return new LastPredictedDepthPort();
    }

    /**
     * Create an instance of {@link DispatchStack }
     * 
     */
    public DispatchStack createDispatchStack() {
        return new DispatchStack();
    }

    /**
     * Create an instance of {@link Iteration }
     * 
     */
    public Iteration createIteration() {
        return new Iteration();
    }

    /**
     * Create an instance of {@link DepthPort }
     * 
     */
    public DepthPort createDepthPort() {
        return new DepthPort();
    }

    /**
     * Create an instance of {@link Datalinks }
     * 
     */
    public Datalinks createDatalinks() {
        return new Datalinks();
    }

    /**
     * Create an instance of {@link IterationNodeParent }
     * 
     */
    public IterationNodeParent createIterationNodeParent() {
        return new IterationNodeParent();
    }

    /**
     * Create an instance of {@link Activities }
     * 
     */
    public Activities createActivities() {
        return new Activities();
    }

    /**
     * Create an instance of {@link Condition }
     * 
     */
    public Condition createCondition() {
        return new Condition();
    }

    /**
     * Create an instance of {@link Ports }
     * 
     */
    public Ports createPorts() {
        return new Ports();
    }

    /**
     * Create an instance of {@link ConfigBean }
     * 
     */
    public ConfigBean createConfigBean() {
        return new ConfigBean();
    }

    /**
     * Create an instance of {@link GranularDepthPorts }
     * 
     */
    public GranularDepthPorts createGranularDepthPorts() {
        return new GranularDepthPorts();
    }

    /**
     * Create an instance of {@link CrossProduct }
     * 
     */
    public CrossProduct createCrossProduct() {
        return new CrossProduct();
    }

    /**
     * Create an instance of {@link DotProduct }
     * 
     */
    public DotProduct createDotProduct() {
        return new DotProduct();
    }

    /**
     * Create an instance of {@link Dataflow }
     * 
     */
    public Dataflow createDataflow() {
        return new Dataflow();
    }

    /**
     * Create an instance of {@link ApiConsumerParameterNames }
     * 
     */
    public ApiConsumerParameterNames createApiConsumerParameterNames() {
        return new ApiConsumerParameterNames();
    }

    /**
     * Create an instance of {@link BioMobyParserConfig }
     * 
     */
    public BioMobyParserConfig createBioMobyParserConfig() {
        return new BioMobyParserConfig();
    }

    /**
     * Create an instance of {@link SpreadsheetColumnNameEntry }
     * 
     */
    public SpreadsheetColumnNameEntry createSpreadsheetColumnNameEntry() {
        return new SpreadsheetColumnNameEntry();
    }

    /**
     * Create an instance of {@link ApiConsumerParameterDimensions }
     * 
     */
    public ApiConsumerParameterDimensions createApiConsumerParameterDimensions() {
        return new ApiConsumerParameterDimensions();
    }

    /**
     * Create an instance of {@link BasicArtifact }
     * 
     */
    public BasicArtifact createBasicArtifact() {
        return new BasicArtifact();
    }

    /**
     * Create an instance of {@link RShellConfig }
     * 
     */
    public RShellConfig createRShellConfig() {
        return new RShellConfig();
    }

    /**
     * Create an instance of {@link BioMobyServiceType }
     * 
     */
    public BioMobyServiceType createBioMobyServiceType() {
        return new BioMobyServiceType();
    }

    /**
     * Create an instance of {@link StringConstantConfig }
     * 
     */
    public StringConstantConfig createStringConstantConfig() {
        return new StringConstantConfig();
    }

    /**
     * Create an instance of {@link ArtifactDependencies }
     * 
     */
    public ArtifactDependencies createArtifactDependencies() {
        return new ArtifactDependencies();
    }

    /**
     * Create an instance of {@link SpreadsheetRange }
     * 
     */
    public SpreadsheetRange createSpreadsheetRange() {
        return new SpreadsheetRange();
    }

    /**
     * Create an instance of {@link RShellConnection }
     * 
     */
    public RShellConnection createRShellConnection() {
        return new RShellConnection();
    }

    /**
     * Create an instance of {@link BioMobyObjectConfig }
     * 
     */
    public BioMobyObjectConfig createBioMobyObjectConfig() {
        return new BioMobyObjectConfig();
    }

    /**
     * Create an instance of {@link BioMobyConfig }
     * 
     */
    public BioMobyConfig createBioMobyConfig() {
        return new BioMobyConfig();
    }

    /**
     * Create an instance of {@link Dependencies }
     * 
     */
    public Dependencies createDependencies() {
        return new Dependencies();
    }

    /**
     * Create an instance of {@link BioMobyCategory }
     * 
     */
    public BioMobyCategory createBioMobyCategory() {
        return new BioMobyCategory();
    }

    /**
     * Create an instance of {@link SpreadsheetExcludes }
     * 
     */
    public SpreadsheetExcludes createSpreadsheetExcludes() {
        return new SpreadsheetExcludes();
    }

    /**
     * Create an instance of {@link BeanshellConfig }
     * 
     */
    public BeanshellConfig createBeanshellConfig() {
        return new BeanshellConfig();
    }

    /**
     * Create an instance of {@link ApiConsumerConfig }
     * 
     */
    public ApiConsumerConfig createApiConsumerConfig() {
        return new ApiConsumerConfig();
    }

    /**
     * Create an instance of {@link SoaplabConfig }
     * 
     */
    public SoaplabConfig createSoaplabConfig() {
        return new SoaplabConfig();
    }

    /**
     * Create an instance of {@link XMLSplitterConfig }
     * 
     */
    public XMLSplitterConfig createXMLSplitterConfig() {
        return new XMLSplitterConfig();
    }

    /**
     * Create an instance of {@link ApiConsumerParameterTypes }
     * 
     */
    public ApiConsumerParameterTypes createApiConsumerParameterTypes() {
        return new ApiConsumerParameterTypes();
    }

    /**
     * Create an instance of {@link ActivityInputPorts }
     * 
     */
    public ActivityInputPorts createActivityInputPorts() {
        return new ActivityInputPorts();
    }

    /**
     * Create an instance of {@link DependencyElement }
     * 
     */
    public DependencyElement createDependencyElement() {
        return new DependencyElement();
    }

    /**
     * Create an instance of {@link WSDLConfig }
     * 
     */
    public WSDLConfig createWSDLConfig() {
        return new WSDLConfig();
    }

    /**
     * Create an instance of {@link BioMobySecondaries }
     * 
     */
    public BioMobySecondaries createBioMobySecondaries() {
        return new BioMobySecondaries();
    }

    /**
     * Create an instance of {@link BioMobyEntry }
     * 
     */
    public BioMobyEntry createBioMobyEntry() {
        return new BioMobyEntry();
    }

    /**
     * Create an instance of {@link ActivityOutputPorts }
     * 
     */
    public ActivityOutputPorts createActivityOutputPorts() {
        return new ActivityOutputPorts();
    }

    /**
     * Create an instance of {@link SpreadsheetColumnNames }
     * 
     */
    public SpreadsheetColumnNames createSpreadsheetColumnNames() {
        return new SpreadsheetColumnNames();
    }

    /**
     * Create an instance of {@link LocalDependencies }
     * 
     */
    public LocalDependencies createLocalDependencies() {
        return new LocalDependencies();
    }

    /**
     * Create an instance of {@link DataflowConfig }
     * 
     */
    public DataflowConfig createDataflowConfig() {
        return new DataflowConfig();
    }

    /**
     * Create an instance of {@link SpreadsheetImportConfig }
     * 
     */
    public SpreadsheetImportConfig createSpreadsheetImportConfig() {
        return new SpreadsheetImportConfig();
    }

    /**
     * Create an instance of {@link RetryConfig }
     * 
     */
    public RetryConfig createRetryConfig() {
        return new RetryConfig();
    }

    /**
     * Create an instance of {@link LoopConfig }
     * 
     */
    public LoopConfig createLoopConfig() {
        return new LoopConfig();
    }

    /**
     * Create an instance of {@link Properties }
     * 
     */
    public Properties createProperties() {
        return new Properties();
    }

    /**
     * Create an instance of {@link ParallelizeConfig }
     * 
     */
    public ParallelizeConfig createParallelizeConfig() {
        return new ParallelizeConfig();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link ActivityPortDefinitionBean.MimeTypes }
     * 
     */
    public ActivityPortDefinitionBean.MimeTypes createActivityPortDefinitionBeanMimeTypes() {
        return new ActivityPortDefinitionBean.MimeTypes();
    }

    /**
     * Create an instance of {@link RShellSymanticType.RShellPortSymanticTypeBean.SymanticType }
     * 
     */
    public RShellSymanticType.RShellPortSymanticTypeBean.SymanticType createRShellSymanticTypeRShellPortSymanticTypeBeanSymanticType() {
        return new RShellSymanticType.RShellPortSymanticTypeBean.SymanticType();
    }

    /**
     * Create an instance of {@link BioMartConfig.MartService }
     * 
     */
    public BioMartConfig.MartService createBioMartConfigMartService() {
        return new BioMartConfig.MartService();
    }

    /**
     * Create an instance of {@link OriginalConfigBean }
     * 
     */
    public OriginalConfigBean createOriginalConfigBean() {
        return new OriginalConfigBean();
    }

    /**
     * Create an instance of {@link AnnotationAssertionImpl.NetSfTavernaT2AnnotationAnnotationAssertionImpl }
     * 
     */
    public AnnotationAssertionImpl.NetSfTavernaT2AnnotationAnnotationAssertionImpl createAnnotationAssertionImplNetSfTavernaT2AnnotationAnnotationAssertionImpl() {
        return new AnnotationAssertionImpl.NetSfTavernaT2AnnotationAnnotationAssertionImpl();
    }

    /**
     * Create an instance of {@link AnnotationChain.NetSfTavernaT2AnnotationAnnotationChainImpl }
     * 
     */
    public AnnotationChain.NetSfTavernaT2AnnotationAnnotationChainImpl createAnnotationChainNetSfTavernaT2AnnotationAnnotationChainImpl() {
        return new AnnotationChain.NetSfTavernaT2AnnotationAnnotationChainImpl();
    }

    /**
     * Create an instance of {@link ActivityInputs.Entry }
     * 
     */
    public ActivityInputs.Entry createActivityInputsEntry() {
        return new ActivityInputs.Entry();
    }

    /**
     * Create an instance of {@link ScriptInputStatic.Content }
     * 
     */
    public ScriptInputStatic.Content createScriptInputStaticContent() {
        return new ScriptInputStatic.Content();
    }

    /**
     * Create an instance of {@link HTTPHeaders.List }
     * 
     */
    public HTTPHeaders.List createHTTPHeadersList() {
        return new HTTPHeaders.List();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExternalToolConfig }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "net.sf.taverna.t2.activities.externaltool.ExternalToolActivityConfigurationBean", substitutionHeadNamespace = "http://taverna.sf.net/2008/xml/t2flow", substitutionHeadName = "abstractConfigBean")
    public JAXBElement<ExternalToolConfig> createNetSfTavernaT2ActivitiesExternaltoolExternalToolActivityConfigurationBean(ExternalToolConfig value) {
        return new JAXBElement<ExternalToolConfig>(_NetSfTavernaT2ActivitiesExternaltoolExternalToolActivityConfigurationBean_QNAME, ExternalToolConfig.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InteractionConfig }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "net.sf.taverna.t2.activities.interaction.InteractionActivityConfigurationBean", substitutionHeadNamespace = "http://taverna.sf.net/2008/xml/t2flow", substitutionHeadName = "abstractConfigBean")
    public JAXBElement<InteractionConfig> createNetSfTavernaT2ActivitiesInteractionInteractionActivityConfigurationBean(InteractionConfig value) {
        return new JAXBElement<InteractionConfig>(_NetSfTavernaT2ActivitiesInteractionInteractionActivityConfigurationBean_QNAME, InteractionConfig.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Workflow }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://taverna.sf.net/2008/xml/t2flow", name = "workflow")
    public JAXBElement<Workflow> createWorkflow(Workflow value) {
        return new JAXBElement<Workflow>(_Workflow_QNAME, Workflow.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UsecaseConfig }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "net.sf.taverna.t2.activities.usecase.UseCaseActivityConfigurationBean", substitutionHeadNamespace = "http://taverna.sf.net/2008/xml/t2flow", substitutionHeadName = "abstractConfigBean")
    public JAXBElement<UsecaseConfig> createNetSfTavernaT2ActivitiesUsecaseUseCaseActivityConfigurationBean(UsecaseConfig value) {
        return new JAXBElement<UsecaseConfig>(_NetSfTavernaT2ActivitiesUsecaseUseCaseActivityConfigurationBean_QNAME, UsecaseConfig.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ComponentConfig }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "net.sf.taverna.t2.component.ComponentActivityConfigurationBean", substitutionHeadNamespace = "http://taverna.sf.net/2008/xml/t2flow", substitutionHeadName = "abstractConfigBean")
    public JAXBElement<ComponentConfig> createNetSfTavernaT2ComponentComponentActivityConfigurationBean(ComponentConfig value) {
        return new JAXBElement<ComponentConfig>(_NetSfTavernaT2ComponentComponentActivityConfigurationBean_QNAME, ComponentConfig.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RESTConfig }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "net.sf.taverna.t2.activities.rest.RESTActivityConfigurationBean", substitutionHeadNamespace = "http://taverna.sf.net/2008/xml/t2flow", substitutionHeadName = "abstractConfigBean")
    public JAXBElement<RESTConfig> createNetSfTavernaT2ActivitiesRestRESTActivityConfigurationBean(RESTConfig value) {
        return new JAXBElement<RESTConfig>(_NetSfTavernaT2ActivitiesRestRESTActivityConfigurationBean_QNAME, RESTConfig.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractConfigBean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://taverna.sf.net/2008/xml/t2flow", name = "abstractConfigBean")
    public JAXBElement<AbstractConfigBean> createAbstractConfigBean(AbstractConfigBean value) {
        return new JAXBElement<AbstractConfigBean>(_AbstractConfigBean_QNAME, AbstractConfigBean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "allowsLiteralValues", scope = ActivityPortDefinitionBean.class)
    public JAXBElement<Boolean> createActivityPortDefinitionBeanAllowsLiteralValues(Boolean value) {
        return new JAXBElement<Boolean>(_ActivityPortDefinitionBeanAllowsLiteralValues_QNAME, Boolean.class, ActivityPortDefinitionBean.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "granularDepth", scope = ActivityPortDefinitionBean.class)
    public JAXBElement<BigInteger> createActivityPortDefinitionBeanGranularDepth(BigInteger value) {
        return new JAXBElement<BigInteger>(_ActivityPortDefinitionBeanGranularDepth_QNAME, BigInteger.class, ActivityPortDefinitionBean.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActivityPortDefinitionBean.MimeTypes }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mimeTypes", scope = ActivityPortDefinitionBean.class)
    public JAXBElement<ActivityPortDefinitionBean.MimeTypes> createActivityPortDefinitionBeanMimeTypes(ActivityPortDefinitionBean.MimeTypes value) {
        return new JAXBElement<ActivityPortDefinitionBean.MimeTypes>(_ActivityPortDefinitionBeanMimeTypes_QNAME, ActivityPortDefinitionBean.MimeTypes.class, ActivityPortDefinitionBean.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "depth", scope = ActivityPortDefinitionBean.class)
    public JAXBElement<BigInteger> createActivityPortDefinitionBeanDepth(BigInteger value) {
        return new JAXBElement<BigInteger>(_ActivityPortDefinitionBeanDepth_QNAME, BigInteger.class, ActivityPortDefinitionBean.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "translatedElementType", scope = ActivityPortDefinitionBean.class)
    public JAXBElement<String> createActivityPortDefinitionBeanTranslatedElementType(String value) {
        return new JAXBElement<String>(_ActivityPortDefinitionBeanTranslatedElementType_QNAME, String.class, ActivityPortDefinitionBean.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "handledReferenceSchemes", scope = ActivityPortDefinitionBean.class)
    public JAXBElement<String> createActivityPortDefinitionBeanHandledReferenceSchemes(String value) {
        return new JAXBElement<String>(_ActivityPortDefinitionBeanHandledReferenceSchemes_QNAME, String.class, ActivityPortDefinitionBean.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "name", scope = ActivityPortDefinitionBean.class)
    public JAXBElement<String> createActivityPortDefinitionBeanName(String value) {
        return new JAXBElement<String>(_ActivityPortDefinitionBeanName_QNAME, String.class, ActivityPortDefinitionBean.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnnotationChain }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://taverna.sf.net/2008/xml/t2flow", name = "annotation_chain_2_2", scope = Annotations.class)
    public JAXBElement<AnnotationChain> createAnnotationsAnnotationChain22(AnnotationChain value) {
        return new JAXBElement<AnnotationChain>(_AnnotationsAnnotationChain22_QNAME, AnnotationChain.class, Annotations.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnnotationChain }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://taverna.sf.net/2008/xml/t2flow", name = "annotation_chain", scope = Annotations.class)
    public JAXBElement<AnnotationChain> createAnnotationsAnnotationChain(AnnotationChain value) {
        return new JAXBElement<AnnotationChain>(_AnnotationsAnnotationChain_QNAME, AnnotationChain.class, Annotations.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "string", scope = HTTPHeaders.List.class)
    public JAXBElement<String> createHTTPHeadersListString(String value) {
        return new JAXBElement<String>(_HTTPHeadersListString_QNAME, String.class, HTTPHeaders.List.class, value);
    }

}
