//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:00:21 PM CET 
//


package org.kit.scufl.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A processor of a dataflow. A processor is a dataflow
 * 				unit that receives input to its input ports, iterates over it using
 * 				the iteration strategy stack, and pushes it down the dispatch stack
 * 				to reach the activities that invokes the actual services. The
 * 				outputs from the services buble up through the dispatch stack and is
 * 				pushed out on the output ports, indexed according to the iteration
 * 				strategy.
 * 			
 * 
 * <p>Java class for Processor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Processor">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://taverna.sf.net/2008/xml/t2flow}ProcessorName"/>
 *         &lt;element name="inputPorts" type="{http://taverna.sf.net/2008/xml/t2flow}DepthPorts"/>
 *         &lt;element name="outputPorts" type="{http://taverna.sf.net/2008/xml/t2flow}GranularDepthPorts"/>
 *         &lt;element name="annotations" type="{http://taverna.sf.net/2008/xml/t2flow}Annotations" minOccurs="0"/>
 *         &lt;element name="activities" type="{http://taverna.sf.net/2008/xml/t2flow}Activities"/>
 *         &lt;element name="dispatchStack" type="{http://taverna.sf.net/2008/xml/t2flow}DispatchStack"/>
 *         &lt;element name="iterationStrategyStack" type="{http://taverna.sf.net/2008/xml/t2flow}IterationStrategyStack"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Processor", propOrder = {
    "name",
    "inputPorts",
    "outputPorts",
    "annotations",
    "activities",
    "dispatchStack",
    "iterationStrategyStack"
})
public class Processor {

    @XmlElement(namespace = "http://taverna.sf.net/2008/xml/t2flow", required = true)
    protected String name;
    @XmlElement(namespace = "http://taverna.sf.net/2008/xml/t2flow", required = true)
    protected DepthPorts inputPorts;
    @XmlElement(namespace = "http://taverna.sf.net/2008/xml/t2flow", required = true)
    protected GranularDepthPorts outputPorts;
    @XmlElement(namespace = "http://taverna.sf.net/2008/xml/t2flow")
    protected Annotations annotations;
    @XmlElement(namespace = "http://taverna.sf.net/2008/xml/t2flow", required = true)
    protected Activities activities;
    @XmlElement(namespace = "http://taverna.sf.net/2008/xml/t2flow", required = true)
    protected DispatchStack dispatchStack;
    @XmlElement(namespace = "http://taverna.sf.net/2008/xml/t2flow", required = true)
    protected IterationStrategyStack iterationStrategyStack;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the inputPorts property.
     * 
     * @return
     *     possible object is
     *     {@link DepthPorts }
     *     
     */
    public DepthPorts getInputPorts() {
        return inputPorts;
    }

    /**
     * Sets the value of the inputPorts property.
     * 
     * @param value
     *     allowed object is
     *     {@link DepthPorts }
     *     
     */
    public void setInputPorts(DepthPorts value) {
        this.inputPorts = value;
    }

    /**
     * Gets the value of the outputPorts property.
     * 
     * @return
     *     possible object is
     *     {@link GranularDepthPorts }
     *     
     */
    public GranularDepthPorts getOutputPorts() {
        return outputPorts;
    }

    /**
     * Sets the value of the outputPorts property.
     * 
     * @param value
     *     allowed object is
     *     {@link GranularDepthPorts }
     *     
     */
    public void setOutputPorts(GranularDepthPorts value) {
        this.outputPorts = value;
    }

    /**
     * Gets the value of the annotations property.
     * 
     * @return
     *     possible object is
     *     {@link Annotations }
     *     
     */
    public Annotations getAnnotations() {
        return annotations;
    }

    /**
     * Sets the value of the annotations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Annotations }
     *     
     */
    public void setAnnotations(Annotations value) {
        this.annotations = value;
    }

    /**
     * Gets the value of the activities property.
     * 
     * @return
     *     possible object is
     *     {@link Activities }
     *     
     */
    public Activities getActivities() {
        return activities;
    }

    /**
     * Sets the value of the activities property.
     * 
     * @param value
     *     allowed object is
     *     {@link Activities }
     *     
     */
    public void setActivities(Activities value) {
        this.activities = value;
    }

    /**
     * Gets the value of the dispatchStack property.
     * 
     * @return
     *     possible object is
     *     {@link DispatchStack }
     *     
     */
    public DispatchStack getDispatchStack() {
        return dispatchStack;
    }

    /**
     * Sets the value of the dispatchStack property.
     * 
     * @param value
     *     allowed object is
     *     {@link DispatchStack }
     *     
     */
    public void setDispatchStack(DispatchStack value) {
        this.dispatchStack = value;
    }

    /**
     * Gets the value of the iterationStrategyStack property.
     * 
     * @return
     *     possible object is
     *     {@link IterationStrategyStack }
     *     
     */
    public IterationStrategyStack getIterationStrategyStack() {
        return iterationStrategyStack;
    }

    /**
     * Sets the value of the iterationStrategyStack property.
     * 
     * @param value
     *     allowed object is
     *     {@link IterationStrategyStack }
     *     
     */
    public void setIterationStrategyStack(IterationStrategyStack value) {
        this.iterationStrategyStack = value;
    }

}
