//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:00:21 PM CET 
//


package org.kit.scufl.api;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Defines parameters of retries for when an
 * 				activity fails.
 * 
 * 
 * <p>Java class for RetryConfig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RetryConfig">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="backoffFactor" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="initialDelay" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="maxDelay" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="maxRetries" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RetryConfig", namespace = "http://taverna.sf.net/2008/xml/t2layers", propOrder = {
    "backoffFactor",
    "initialDelay",
    "maxDelay",
    "maxRetries"
})
public class RetryConfig {

    protected double backoffFactor;
    protected long initialDelay;
    protected long maxDelay;
    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger maxRetries;

    /**
     * Gets the value of the backoffFactor property.
     * 
     */
    public double getBackoffFactor() {
        return backoffFactor;
    }

    /**
     * Sets the value of the backoffFactor property.
     * 
     */
    public void setBackoffFactor(double value) {
        this.backoffFactor = value;
    }

    /**
     * Gets the value of the initialDelay property.
     * 
     */
    public long getInitialDelay() {
        return initialDelay;
    }

    /**
     * Sets the value of the initialDelay property.
     * 
     */
    public void setInitialDelay(long value) {
        this.initialDelay = value;
    }

    /**
     * Gets the value of the maxDelay property.
     * 
     */
    public long getMaxDelay() {
        return maxDelay;
    }

    /**
     * Sets the value of the maxDelay property.
     * 
     */
    public void setMaxDelay(long value) {
        this.maxDelay = value;
    }

    /**
     * Gets the value of the maxRetries property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxRetries() {
        return maxRetries;
    }

    /**
     * Sets the value of the maxRetries property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxRetries(BigInteger value) {
        this.maxRetries = value;
    }

}
