//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:00:21 PM CET 
//


package org.kit.scufl.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RShellConfig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RShellConfig">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="inputs" type="{http://taverna.sf.net/2008/xml/t2activities}ActivityInputPorts"/>
 *         &lt;element name="outputs" type="{http://taverna.sf.net/2008/xml/t2activities}ActivityOutputPorts"/>
 *         &lt;element name="rVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="script" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="connectionSettings" type="{http://taverna.sf.net/2008/xml/t2activities}RShellConnection"/>
 *         &lt;element name="inputSymanticTypes" type="{http://taverna.sf.net/2008/xml/t2activities}RShellSymanticType"/>
 *         &lt;element name="outputSymanticTypes" type="{http://taverna.sf.net/2008/xml/t2activities}RShellSymanticType"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RShellConfig", namespace = "http://taverna.sf.net/2008/xml/t2activities", propOrder = {

})
public class RShellConfig {

    @XmlElement(required = true)
    protected ActivityInputPorts inputs;
    @XmlElement(required = true)
    protected ActivityOutputPorts outputs;
    protected String rVersion;
    @XmlElement(required = true)
    protected String script;
    @XmlElement(required = true)
    protected RShellConnection connectionSettings;
    @XmlElement(required = true)
    protected RShellSymanticType inputSymanticTypes;
    @XmlElement(required = true)
    protected RShellSymanticType outputSymanticTypes;

    /**
     * Gets the value of the inputs property.
     * 
     * @return
     *     possible object is
     *     {@link ActivityInputPorts }
     *     
     */
    public ActivityInputPorts getInputs() {
        return inputs;
    }

    /**
     * Sets the value of the inputs property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActivityInputPorts }
     *     
     */
    public void setInputs(ActivityInputPorts value) {
        this.inputs = value;
    }

    /**
     * Gets the value of the outputs property.
     * 
     * @return
     *     possible object is
     *     {@link ActivityOutputPorts }
     *     
     */
    public ActivityOutputPorts getOutputs() {
        return outputs;
    }

    /**
     * Sets the value of the outputs property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActivityOutputPorts }
     *     
     */
    public void setOutputs(ActivityOutputPorts value) {
        this.outputs = value;
    }

    /**
     * Gets the value of the rVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRVersion() {
        return rVersion;
    }

    /**
     * Sets the value of the rVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRVersion(String value) {
        this.rVersion = value;
    }

    /**
     * Gets the value of the script property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScript() {
        return script;
    }

    /**
     * Sets the value of the script property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScript(String value) {
        this.script = value;
    }

    /**
     * Gets the value of the connectionSettings property.
     * 
     * @return
     *     possible object is
     *     {@link RShellConnection }
     *     
     */
    public RShellConnection getConnectionSettings() {
        return connectionSettings;
    }

    /**
     * Sets the value of the connectionSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link RShellConnection }
     *     
     */
    public void setConnectionSettings(RShellConnection value) {
        this.connectionSettings = value;
    }

    /**
     * Gets the value of the inputSymanticTypes property.
     * 
     * @return
     *     possible object is
     *     {@link RShellSymanticType }
     *     
     */
    public RShellSymanticType getInputSymanticTypes() {
        return inputSymanticTypes;
    }

    /**
     * Sets the value of the inputSymanticTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link RShellSymanticType }
     *     
     */
    public void setInputSymanticTypes(RShellSymanticType value) {
        this.inputSymanticTypes = value;
    }

    /**
     * Gets the value of the outputSymanticTypes property.
     * 
     * @return
     *     possible object is
     *     {@link RShellSymanticType }
     *     
     */
    public RShellSymanticType getOutputSymanticTypes() {
        return outputSymanticTypes;
    }

    /**
     * Sets the value of the outputSymanticTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link RShellSymanticType }
     *     
     */
    public void setOutputSymanticTypes(RShellSymanticType value) {
        this.outputSymanticTypes = value;
    }

}
