//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:00:21 PM CET 
//


package org.kit.scufl.api;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Configuration for the SoapLab activity.
 * 			
 * 
 * <p>Java class for SoaplabConfig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SoaplabConfig">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="endpoint" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="pollingInterval" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="pollingBackoff" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="pollingIntervalMax" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SoaplabConfig", namespace = "http://taverna.sf.net/2008/xml/t2activities", propOrder = {
    "endpoint",
    "pollingInterval",
    "pollingBackoff",
    "pollingIntervalMax"
})
public class SoaplabConfig {

    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String endpoint;
    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger pollingInterval;
    protected double pollingBackoff;
    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger pollingIntervalMax;

    /**
     * Gets the value of the endpoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndpoint() {
        return endpoint;
    }

    /**
     * Sets the value of the endpoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndpoint(String value) {
        this.endpoint = value;
    }

    /**
     * Gets the value of the pollingInterval property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPollingInterval() {
        return pollingInterval;
    }

    /**
     * Sets the value of the pollingInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPollingInterval(BigInteger value) {
        this.pollingInterval = value;
    }

    /**
     * Gets the value of the pollingBackoff property.
     * 
     */
    public double getPollingBackoff() {
        return pollingBackoff;
    }

    /**
     * Sets the value of the pollingBackoff property.
     * 
     */
    public void setPollingBackoff(double value) {
        this.pollingBackoff = value;
    }

    /**
     * Gets the value of the pollingIntervalMax property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPollingIntervalMax() {
        return pollingIntervalMax;
    }

    /**
     * Sets the value of the pollingIntervalMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPollingIntervalMax(BigInteger value) {
        this.pollingIntervalMax = value;
    }

}
