//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:00:21 PM CET 
//


package org.kit.scufl.api;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpreadsheetEmptyCellPolicy.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SpreadsheetEmptyCellPolicy">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="EMPTY_STRING"/>
 *     &lt;enumeration value="USER_DEFINED"/>
 *     &lt;enumeration value="GENERATE_ERROR"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SpreadsheetEmptyCellPolicy", namespace = "http://taverna.sf.net/2008/xml/t2activities")
@XmlEnum
public enum SpreadsheetEmptyCellPolicy {

    EMPTY_STRING,
    USER_DEFINED,
    GENERATE_ERROR;

    public String value() {
        return name();
    }

    public static SpreadsheetEmptyCellPolicy fromValue(String v) {
        return valueOf(v);
    }

}
