//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:00:21 PM CET 
//


package org.kit.scufl.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TopIterationNode complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TopIterationNode">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice minOccurs="0">
 *         &lt;element name="cross" type="{http://taverna.sf.net/2008/xml/t2flow}CrossProduct"/>
 *         &lt;element name="dot" type="{http://taverna.sf.net/2008/xml/t2flow}DotProduct"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TopIterationNode", propOrder = {
    "cross",
    "dot"
})
public class TopIterationNode {

    @XmlElement(namespace = "http://taverna.sf.net/2008/xml/t2flow")
    protected CrossProduct cross;
    @XmlElement(namespace = "http://taverna.sf.net/2008/xml/t2flow")
    protected DotProduct dot;

    /**
     * Gets the value of the cross property.
     * 
     * @return
     *     possible object is
     *     {@link CrossProduct }
     *     
     */
    public CrossProduct getCross() {
        return cross;
    }

    /**
     * Sets the value of the cross property.
     * 
     * @param value
     *     allowed object is
     *     {@link CrossProduct }
     *     
     */
    public void setCross(CrossProduct value) {
        this.cross = value;
    }

    /**
     * Gets the value of the dot property.
     * 
     * @return
     *     possible object is
     *     {@link DotProduct }
     *     
     */
    public DotProduct getDot() {
        return dot;
    }

    /**
     * Sets the value of the dot property.
     * 
     * @param value
     *     allowed object is
     *     {@link DotProduct }
     *     
     */
    public void setDot(DotProduct value) {
        this.dot = value;
    }

}
