//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:00:21 PM CET 
//


package org.kit.scufl.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UsecaseDescription complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UsecaseDescription">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="usecaseid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="group" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="command" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="test__local" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="preparingTimeoutInSeconds" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="executionTimeoutInSeconds" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="tags" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="REs" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="queue__preferred" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="queue__deny" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="static__inputs" type="{}StaticInputs"/>
 *         &lt;element name="inputs" type="{}EntryMap"/>
 *         &lt;element name="outputs" type="{}EntryMap"/>
 *         &lt;element name="includeStdIn" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="includeStdOut" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="includeStdErr" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="validReturnCodes" type="{}ReturnCodes"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UsecaseDescription", namespace = "", propOrder = {
    "usecaseid",
    "group",
    "description",
    "command",
    "testLocal",
    "preparingTimeoutInSeconds",
    "executionTimeoutInSeconds",
    "tags",
    "rEs",
    "queuePreferred",
    "queueDeny",
    "staticInputs",
    "inputs",
    "outputs",
    "includeStdIn",
    "includeStdOut",
    "includeStdErr",
    "validReturnCodes"
})
public class UsecaseDescription {

    @XmlElement(required = true)
    protected String usecaseid;
    protected String group;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected String command;
    @XmlElement(name = "test__local")
    protected String testLocal;
    protected int preparingTimeoutInSeconds;
    protected int executionTimeoutInSeconds;
    @XmlElement(required = true)
    protected Object tags;
    @XmlElement(name = "REs", required = true)
    protected Object rEs;
    @XmlElement(name = "queue__preferred", required = true)
    protected Object queuePreferred;
    @XmlElement(name = "queue__deny", required = true)
    protected Object queueDeny;
    @XmlElement(name = "static__inputs", required = true)
    protected StaticInputs staticInputs;
    @XmlElement(required = true)
    protected EntryMap inputs;
    @XmlElement(required = true)
    protected EntryMap outputs;
    protected boolean includeStdIn;
    protected boolean includeStdOut;
    protected boolean includeStdErr;
    @XmlElement(required = true)
    protected ReturnCodes validReturnCodes;

    /**
     * Gets the value of the usecaseid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsecaseid() {
        return usecaseid;
    }

    /**
     * Sets the value of the usecaseid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsecaseid(String value) {
        this.usecaseid = value;
    }

    /**
     * Gets the value of the group property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroup() {
        return group;
    }

    /**
     * Sets the value of the group property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroup(String value) {
        this.group = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the command property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommand() {
        return command;
    }

    /**
     * Sets the value of the command property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommand(String value) {
        this.command = value;
    }

    /**
     * Gets the value of the testLocal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestLocal() {
        return testLocal;
    }

    /**
     * Sets the value of the testLocal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestLocal(String value) {
        this.testLocal = value;
    }

    /**
     * Gets the value of the preparingTimeoutInSeconds property.
     * 
     */
    public int getPreparingTimeoutInSeconds() {
        return preparingTimeoutInSeconds;
    }

    /**
     * Sets the value of the preparingTimeoutInSeconds property.
     * 
     */
    public void setPreparingTimeoutInSeconds(int value) {
        this.preparingTimeoutInSeconds = value;
    }

    /**
     * Gets the value of the executionTimeoutInSeconds property.
     * 
     */
    public int getExecutionTimeoutInSeconds() {
        return executionTimeoutInSeconds;
    }

    /**
     * Sets the value of the executionTimeoutInSeconds property.
     * 
     */
    public void setExecutionTimeoutInSeconds(int value) {
        this.executionTimeoutInSeconds = value;
    }

    /**
     * Gets the value of the tags property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getTags() {
        return tags;
    }

    /**
     * Sets the value of the tags property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setTags(Object value) {
        this.tags = value;
    }

    /**
     * Gets the value of the rEs property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getREs() {
        return rEs;
    }

    /**
     * Sets the value of the rEs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setREs(Object value) {
        this.rEs = value;
    }

    /**
     * Gets the value of the queuePreferred property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getQueuePreferred() {
        return queuePreferred;
    }

    /**
     * Sets the value of the queuePreferred property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setQueuePreferred(Object value) {
        this.queuePreferred = value;
    }

    /**
     * Gets the value of the queueDeny property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getQueueDeny() {
        return queueDeny;
    }

    /**
     * Sets the value of the queueDeny property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setQueueDeny(Object value) {
        this.queueDeny = value;
    }

    /**
     * Gets the value of the staticInputs property.
     * 
     * @return
     *     possible object is
     *     {@link StaticInputs }
     *     
     */
    public StaticInputs getStaticInputs() {
        return staticInputs;
    }

    /**
     * Sets the value of the staticInputs property.
     * 
     * @param value
     *     allowed object is
     *     {@link StaticInputs }
     *     
     */
    public void setStaticInputs(StaticInputs value) {
        this.staticInputs = value;
    }

    /**
     * Gets the value of the inputs property.
     * 
     * @return
     *     possible object is
     *     {@link EntryMap }
     *     
     */
    public EntryMap getInputs() {
        return inputs;
    }

    /**
     * Sets the value of the inputs property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntryMap }
     *     
     */
    public void setInputs(EntryMap value) {
        this.inputs = value;
    }

    /**
     * Gets the value of the outputs property.
     * 
     * @return
     *     possible object is
     *     {@link EntryMap }
     *     
     */
    public EntryMap getOutputs() {
        return outputs;
    }

    /**
     * Sets the value of the outputs property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntryMap }
     *     
     */
    public void setOutputs(EntryMap value) {
        this.outputs = value;
    }

    /**
     * Gets the value of the includeStdIn property.
     * 
     */
    public boolean isIncludeStdIn() {
        return includeStdIn;
    }

    /**
     * Sets the value of the includeStdIn property.
     * 
     */
    public void setIncludeStdIn(boolean value) {
        this.includeStdIn = value;
    }

    /**
     * Gets the value of the includeStdOut property.
     * 
     */
    public boolean isIncludeStdOut() {
        return includeStdOut;
    }

    /**
     * Sets the value of the includeStdOut property.
     * 
     */
    public void setIncludeStdOut(boolean value) {
        this.includeStdOut = value;
    }

    /**
     * Gets the value of the includeStdErr property.
     * 
     */
    public boolean isIncludeStdErr() {
        return includeStdErr;
    }

    /**
     * Sets the value of the includeStdErr property.
     * 
     */
    public void setIncludeStdErr(boolean value) {
        this.includeStdErr = value;
    }

    /**
     * Gets the value of the validReturnCodes property.
     * 
     * @return
     *     possible object is
     *     {@link ReturnCodes }
     *     
     */
    public ReturnCodes getValidReturnCodes() {
        return validReturnCodes;
    }

    /**
     * Sets the value of the validReturnCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReturnCodes }
     *     
     */
    public void setValidReturnCodes(ReturnCodes value) {
        this.validReturnCodes = value;
    }

}
