//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:00:21 PM CET 
//


package org.kit.scufl.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UsecaseConfig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UsecaseConfig">
 *   &lt;complexContent>
 *     &lt;extension base="{http://taverna.sf.net/2008/xml/t2flow}AbstractConfigBean">
 *       &lt;sequence>
 *         &lt;element name="repositoryUrl" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="usecaseid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UsecaseConfig", namespace = "", propOrder = {
    "repositoryUrl",
    "usecaseid"
})
public class UsecaseConfig
    extends AbstractConfigBean
{

    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String repositoryUrl;
    @XmlElement(required = true)
    protected String usecaseid;

    /**
     * Gets the value of the repositoryUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepositoryUrl() {
        return repositoryUrl;
    }

    /**
     * Sets the value of the repositoryUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepositoryUrl(String value) {
        this.repositoryUrl = value;
    }

    /**
     * Gets the value of the usecaseid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsecaseid() {
        return usecaseid;
    }

    /**
     * Sets the value of the usecaseid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsecaseid(String value) {
        this.usecaseid = value;
    }

}
