//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.09 at 03:17:22 PM CET 
//


package org.kit.xscufl.api;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.kit.xscufl.api package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Scufl_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "scufl");
    private final static QName _SinkTypeMetadata_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "metadata");
    private final static QName _LocalTypeExtensions_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "extensions");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.kit.xscufl.api
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ScuflType }
     * 
     */
    public ScuflType createScuflType() {
        return new ScuflType();
    }

    /**
     * Create an instance of {@link ComplextypeType }
     * 
     */
    public ComplextypeType createComplextypeType() {
        return new ComplextypeType();
    }

    /**
     * Create an instance of {@link WorkflowdescriptionType }
     * 
     */
    public WorkflowdescriptionType createWorkflowdescriptionType() {
        return new WorkflowdescriptionType();
    }

    /**
     * Create an instance of {@link ProcessorType }
     * 
     */
    public ProcessorType createProcessorType() {
        return new ProcessorType();
    }

    /**
     * Create an instance of {@link StatechangeType }
     * 
     */
    public StatechangeType createStatechangeType() {
        return new StatechangeType();
    }

    /**
     * Create an instance of {@link MimeTypesType }
     * 
     */
    public MimeTypesType createMimeTypesType() {
        return new MimeTypesType();
    }

    /**
     * Create an instance of {@link ArraytypeType }
     * 
     */
    public ArraytypeType createArraytypeType() {
        return new ArraytypeType();
    }

    /**
     * Create an instance of {@link WorkflowType }
     * 
     */
    public WorkflowType createWorkflowType() {
        return new WorkflowType();
    }

    /**
     * Create an instance of {@link CoordinationType }
     * 
     */
    public CoordinationType createCoordinationType() {
        return new CoordinationType();
    }

    /**
     * Create an instance of {@link ElementtypeType }
     * 
     */
    public ElementtypeType createElementtypeType() {
        return new ElementtypeType();
    }

    /**
     * Create an instance of {@link DefaultsType }
     * 
     */
    public DefaultsType createDefaultsType() {
        return new DefaultsType();
    }

    /**
     * Create an instance of {@link DependenciesType }
     * 
     */
    public DependenciesType createDependenciesType() {
        return new DependenciesType();
    }

    /**
     * Create an instance of {@link DefaultType }
     * 
     */
    public DefaultType createDefaultType() {
        return new DefaultType();
    }

    /**
     * Create an instance of {@link LocalType }
     * 
     */
    public LocalType createLocalType() {
        return new LocalType();
    }

    /**
     * Create an instance of {@link ElementsType }
     * 
     */
    public ElementsType createElementsType() {
        return new ElementsType();
    }

    /**
     * Create an instance of {@link ActionType }
     * 
     */
    public ActionType createActionType() {
        return new ActionType();
    }

    /**
     * Create an instance of {@link BasetypeType }
     * 
     */
    public BasetypeType createBasetypeType() {
        return new BasetypeType();
    }

    /**
     * Create an instance of {@link BeanshellinputType }
     * 
     */
    public BeanshellinputType createBeanshellinputType() {
        return new BeanshellinputType();
    }

    /**
     * Create an instance of {@link BeanshelloutputType }
     * 
     */
    public BeanshelloutputType createBeanshelloutputType() {
        return new BeanshelloutputType();
    }

    /**
     * Create an instance of {@link BeanshelloutputlistType }
     * 
     */
    public BeanshelloutputlistType createBeanshelloutputlistType() {
        return new BeanshelloutputlistType();
    }

    /**
     * Create an instance of {@link SourceType }
     * 
     */
    public SourceType createSourceType() {
        return new SourceType();
    }

    /**
     * Create an instance of {@link BeanshellinputlistType }
     * 
     */
    public BeanshellinputlistType createBeanshellinputlistType() {
        return new BeanshellinputlistType();
    }

    /**
     * Create an instance of {@link LinkType }
     * 
     */
    public LinkType createLinkType() {
        return new LinkType();
    }

    /**
     * Create an instance of {@link ConditionType }
     * 
     */
    public ConditionType createConditionType() {
        return new ConditionType();
    }

    /**
     * Create an instance of {@link SinkType }
     * 
     */
    public SinkType createSinkType() {
        return new SinkType();
    }

    /**
     * Create an instance of {@link ExtensionsType }
     * 
     */
    public ExtensionsType createExtensionsType() {
        return new ExtensionsType();
    }

    /**
     * Create an instance of {@link BeanshellType }
     * 
     */
    public BeanshellType createBeanshellType() {
        return new BeanshellType();
    }

    /**
     * Create an instance of {@link ArbitrarywsdlType }
     * 
     */
    public ArbitrarywsdlType createArbitrarywsdlType() {
        return new ArbitrarywsdlType();
    }

    /**
     * Create an instance of {@link MetadataType }
     * 
     */
    public MetadataType createMetadataType() {
        return new MetadataType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ScuflType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "scufl")
    public JAXBElement<ScuflType> createScufl(ScuflType value) {
        return new JAXBElement<ScuflType>(_Scufl_QNAME, ScuflType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MetadataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "metadata", scope = SinkType.class)
    public JAXBElement<MetadataType> createSinkTypeMetadata(MetadataType value) {
        return new JAXBElement<MetadataType>(_SinkTypeMetadata_QNAME, MetadataType.class, SinkType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtensionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "extensions", scope = LocalType.class)
    public JAXBElement<ExtensionsType> createLocalTypeExtensions(ExtensionsType value) {
        return new JAXBElement<ExtensionsType>(_LocalTypeExtensions_QNAME, ExtensionsType.class, LocalType.class, value);
    }

}
