//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.09 at 03:17:22 PM CET 
//


package org.kit.xscufl.api;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for processorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="processorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="arbitrarywsdl" type="{http://org.embl.ebi.escience/xscufl/0.1alpha}arbitrarywsdlType"/>
 *         &lt;element name="defaults" type="{http://org.embl.ebi.escience/xscufl/0.1alpha}defaultsType"/>
 *         &lt;element name="local" type="{http://org.embl.ebi.escience/xscufl/0.1alpha}localType"/>
 *         &lt;element name="beanshell" type="{http://org.embl.ebi.escience/xscufl/0.1alpha}beanshellType"/>
 *         &lt;element name="workflow" type="{http://org.embl.ebi.escience/xscufl/0.1alpha}workflowType"/>
 *       &lt;/choice>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "processorType", propOrder = {
    "descriptionOrArbitrarywsdlOrDefaults"
})
public class ProcessorType {

    @XmlElements({
        @XmlElement(name = "description", type = String.class),
        @XmlElement(name = "arbitrarywsdl", type = ArbitrarywsdlType.class),
        @XmlElement(name = "defaults", type = DefaultsType.class),
        @XmlElement(name = "local", type = LocalType.class),
        @XmlElement(name = "beanshell", type = BeanshellType.class),
        @XmlElement(name = "workflow", type = WorkflowType.class)
    })
    protected List<Object> descriptionOrArbitrarywsdlOrDefaults;
    @XmlAttribute(name = "name")
    protected String name;

    /**
     * Gets the value of the descriptionOrArbitrarywsdlOrDefaults property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the descriptionOrArbitrarywsdlOrDefaults property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescriptionOrArbitrarywsdlOrDefaults().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * {@link ArbitrarywsdlType }
     * {@link DefaultsType }
     * {@link LocalType }
     * {@link BeanshellType }
     * {@link WorkflowType }
     * 
     * 
     */
    public List<Object> getDescriptionOrArbitrarywsdlOrDefaults() {
        if (descriptionOrArbitrarywsdlOrDefaults == null) {
            descriptionOrArbitrarywsdlOrDefaults = new ArrayList<Object>();
        }
        return this.descriptionOrArbitrarywsdlOrDefaults;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
