//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.09 at 03:17:22 PM CET 
//


package org.kit.xscufl.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for workflowType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="workflowType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="scufl" type="{http://org.embl.ebi.escience/xscufl/0.1alpha}scuflType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="maxretries" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="retrydelay" type="{http://www.w3.org/2001/XMLSchema}short" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "workflowType", propOrder = {
    "scufl"
})
public class WorkflowType {

    @XmlElement(required = true)
    protected ScuflType scufl;
    @XmlAttribute(name = "maxretries")
    protected Byte maxretries;
    @XmlAttribute(name = "retrydelay")
    protected Short retrydelay;

    /**
     * Gets the value of the scufl property.
     * 
     * @return
     *     possible object is
     *     {@link ScuflType }
     *     
     */
    public ScuflType getScufl() {
        return scufl;
    }

    /**
     * Sets the value of the scufl property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScuflType }
     *     
     */
    public void setScufl(ScuflType value) {
        this.scufl = value;
    }

    /**
     * Gets the value of the maxretries property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getMaxretries() {
        return maxretries;
    }

    /**
     * Sets the value of the maxretries property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setMaxretries(Byte value) {
        this.maxretries = value;
    }

    /**
     * Gets the value of the retrydelay property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getRetrydelay() {
        return retrydelay;
    }

    /**
     * Sets the value of the retrydelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setRetrydelay(Short value) {
        this.retrydelay = value;
    }

}
