//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:01:34 PM CET 
//


package org.kit.scufl.embl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for alternateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="alternateType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://org.embl.ebi.escience/xscufl/0.1alpha}processorType">
 *       &lt;sequence>
 *         &lt;element ref="{http://org.embl.ebi.escience/xscufl/0.1alpha}inputmap" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://org.embl.ebi.escience/xscufl/0.1alpha}outputmap" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "alternateType", propOrder = {
    "inputmap",
    "outputmap"
})
public class AlternateType
    extends ProcessorType
{

    protected List<MapType> inputmap;
    protected List<MapType> outputmap;

    /**
     * Gets the value of the inputmap property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inputmap property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInputmap().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MapType }
     * 
     * 
     */
    public List<MapType> getInputmap() {
        if (inputmap == null) {
            inputmap = new ArrayList<MapType>();
        }
        return this.inputmap;
    }

    /**
     * Gets the value of the outputmap property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the outputmap property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOutputmap().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MapType }
     * 
     * 
     */
    public List<MapType> getOutputmap() {
        if (outputmap == null) {
            outputmap = new ArrayList<MapType>();
        }
        return this.outputmap;
    }

}
