//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:01:34 PM CET 
//


package org.kit.scufl.embl;

import javax.xml.bind.JAXBElement;
import javax.xml.namespace.QName;

public class ApiConsumerParameter
    extends JAXBElement<ApiConsumerParameterType>
{

    protected final static QName NAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "parameter");

    public ApiConsumerParameter(ApiConsumerParameterType value) {
        super(NAME, ((Class) ApiConsumerParameterType.class), null, value);
    }

    public ApiConsumerParameter() {
        super(NAME, ((Class) ApiConsumerParameterType.class), null, null);
    }

}
