//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:01:34 PM CET 
//


package org.kit.scufl.embl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for apiconsumerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="apiconsumerType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://org.embl.ebi.escience/xscufl/0.1alpha}class"/>
 *         &lt;element ref="{http://org.embl.ebi.escience/xscufl/0.1alpha}method"/>
 *         &lt;element ref="{http://org.embl.ebi.escience/xscufl/0.1alpha}description"/>
 *         &lt;sequence>
 *           &lt;element ref="{http://org.embl.ebi.escience/xscufl/0.1alpha}parameter" maxOccurs="unbounded"/>
 *         &lt;/sequence>
 *         &lt;element ref="{http://org.embl.ebi.escience/xscufl/0.1alpha}dependencies"/>
 *         &lt;element ref="{http://org.embl.ebi.escience/xscufl/0.1alpha}repositories"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "apiconsumerType", propOrder = {
    "clazz",
    "method",
    "description",
    "parameter",
    "dependencies",
    "repositories"
})
public class ApiconsumerType {

    @XmlElement(name = "class", required = true)
    protected ClassType clazz;
    @XmlElement(required = true)
    protected MethodType method;
    @XmlElement(required = true)
    protected DescriptionType description;
    @XmlElementRef(name = "parameter", namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", type = ApiConsumerParameter.class)
    protected List<ApiConsumerParameter> parameter;
    @XmlElement(required = true)
    protected DependenciesType dependencies;
    @XmlElement(required = true)
    protected RepositoriesType repositories;

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link ClassType }
     *     
     */
    public ClassType getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassType }
     *     
     */
    public void setClazz(ClassType value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the method property.
     * 
     * @return
     *     possible object is
     *     {@link MethodType }
     *     
     */
    public MethodType getMethod() {
        return method;
    }

    /**
     * Sets the value of the method property.
     * 
     * @param value
     *     allowed object is
     *     {@link MethodType }
     *     
     */
    public void setMethod(MethodType value) {
        this.method = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link DescriptionType }
     *     
     */
    public DescriptionType getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link DescriptionType }
     *     
     */
    public void setDescription(DescriptionType value) {
        this.description = value;
    }

    /**
     * Gets the value of the parameter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parameter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParameter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ApiConsumerParameter }
     * 
     * 
     */
    public List<ApiConsumerParameter> getParameter() {
        if (parameter == null) {
            parameter = new ArrayList<ApiConsumerParameter>();
        }
        return this.parameter;
    }

    /**
     * Gets the value of the dependencies property.
     * 
     * @return
     *     possible object is
     *     {@link DependenciesType }
     *     
     */
    public DependenciesType getDependencies() {
        return dependencies;
    }

    /**
     * Sets the value of the dependencies property.
     * 
     * @param value
     *     allowed object is
     *     {@link DependenciesType }
     *     
     */
    public void setDependencies(DependenciesType value) {
        this.dependencies = value;
    }

    /**
     * Gets the value of the repositories property.
     * 
     * @return
     *     possible object is
     *     {@link RepositoriesType }
     *     
     */
    public RepositoriesType getRepositories() {
        return repositories;
    }

    /**
     * Sets the value of the repositories property.
     * 
     * @param value
     *     allowed object is
     *     {@link RepositoriesType }
     *     
     */
    public void setRepositories(RepositoriesType value) {
        this.repositories = value;
    }

}
