//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:01:34 PM CET 
//


package org.kit.scufl.embl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for biomobyobjectType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="biomobyobjectType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://org.embl.ebi.escience/xscufl/0.1alpha}mobyEndpoint"/>
 *         &lt;element ref="{http://org.embl.ebi.escience/xscufl/0.1alpha}serviceName"/>
 *         &lt;element ref="{http://org.embl.ebi.escience/xscufl/0.1alpha}authorityName"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "biomobyobjectType", propOrder = {
    "mobyEndpoint",
    "serviceName",
    "authorityName"
})
public class BiomobyobjectType {

    @XmlElement(required = true)
    protected MobyEndpointType mobyEndpoint;
    @XmlElement(required = true)
    protected ServiceNameType serviceName;
    @XmlElement(required = true)
    protected AuthorityNameType authorityName;

    /**
     * Gets the value of the mobyEndpoint property.
     * 
     * @return
     *     possible object is
     *     {@link MobyEndpointType }
     *     
     */
    public MobyEndpointType getMobyEndpoint() {
        return mobyEndpoint;
    }

    /**
     * Sets the value of the mobyEndpoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link MobyEndpointType }
     *     
     */
    public void setMobyEndpoint(MobyEndpointType value) {
        this.mobyEndpoint = value;
    }

    /**
     * Gets the value of the serviceName property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceNameType }
     *     
     */
    public ServiceNameType getServiceName() {
        return serviceName;
    }

    /**
     * Sets the value of the serviceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceNameType }
     *     
     */
    public void setServiceName(ServiceNameType value) {
        this.serviceName = value;
    }

    /**
     * Gets the value of the authorityName property.
     * 
     * @return
     *     possible object is
     *     {@link AuthorityNameType }
     *     
     */
    public AuthorityNameType getAuthorityName() {
        return authorityName;
    }

    /**
     * Sets the value of the authorityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthorityNameType }
     *     
     */
    public void setAuthorityName(AuthorityNameType value) {
        this.authorityName = value;
    }

}
