//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:01:34 PM CET 
//


package org.kit.scufl.embl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.kit.scufl.other package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Action_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "action");
    private final static QName _Host_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "host");
    private final static QName _State_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "state");
    private final static QName _From_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "from");
    private final static QName _Stringconstant_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "stringconstant");
    private final static QName _Notification_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "notification");
    private final static QName _Output_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "output");
    private final static QName _Artifact_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "artifact");
    private final static QName _Apiconsumer_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "apiconsumer");
    private final static QName _Iterator_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "iterator");
    private final static QName _Outputmap_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "outputmap");
    private final static QName _Repositories_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "repositories");
    private final static QName _MimeType_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "mimeType");
    private final static QName _Source_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "source");
    private final static QName _Iterationstrategy_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "iterationstrategy");
    private final static QName _OutputPortList_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "outputPortList");
    private final static QName _Arbitrarywsdl_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "arbitrarywsdl");
    private final static QName _Repository_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "repository");
    private final static QName _Coordination_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "coordination");
    private final static QName _Elementtype_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "elementtype");
    private final static QName _Beanshell_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "beanshell");
    private final static QName _AuthorityName_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "authorityName");
    private final static QName _Metadata_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "metadata");
    private final static QName _Beanshelloutput_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "beanshelloutput");
    private final static QName _Input_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "input");
    private final static QName _ProcessorElement_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "processorElement");
    private final static QName _Biomobyparser_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "biomobyparser");
    private final static QName _Arraytype_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "arraytype");
    private final static QName _Condition_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "condition");
    private final static QName _OutputPort_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "outputPort");
    private final static QName _Extensions_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "extensions");
    private final static QName _Port_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "port");
    private final static QName _Defaults_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "defaults");
    private final static QName _SemanticType_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "semanticType");
    private final static QName _TemplatePortReference_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "templatePortReference");
    private final static QName _Scufl_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "scufl");
    private final static QName _Processor_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "processor");
    private final static QName _Dependencies_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "dependencies");
    private final static QName _Biomobyobject_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "biomobyobject");
    private final static QName _Method_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "method");
    private final static QName _Statechange_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "statechange");
    private final static QName _Beanshelloutputlist_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "beanshelloutputlist");
    private final static QName _Sink_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "sink");
    private final static QName _Mergemode_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "mergemode");
    private final static QName _InputPortList_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "inputPortList");
    private final static QName _Class_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "class");
    private final static QName _Inputmap_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "inputmap");
    private final static QName _Flattenlist_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "flattenlist");
    private final static QName _Wsdl_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "wsdl");
    private final static QName _Default_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "default");
    private final static QName _Endpoint_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "endpoint");
    private final static QName _Datatype_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "datatype");
    private final static QName _Abstractprocessor_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "abstractprocessor");
    private final static QName _InputPort_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "inputPort");
    private final static QName _Scriptvalue_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "scriptvalue");
    private final static QName _Complextype_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "complextype");
    private final static QName _Description_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "description");
    private final static QName _Dot_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "dot");
    private final static QName _Link_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "link");
    private final static QName _MobyEndpoint_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "mobyEndpoint");
    private final static QName _RshellOutputPortList_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "rshellOutputPortList");
    private final static QName _Soaplabwsdl_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "soaplabwsdl");
    private final static QName _Local_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "local");
    private final static QName _Template_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "template");
    private final static QName _Biomart_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "biomart");
    private final static QName _RshellInputPort_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "rshellInputPort");
    private final static QName _Biomobywsdl_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "biomobywsdl");
    private final static QName _Jarfile_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "jarfile");
    private final static QName _Basetype_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "basetype");
    private final static QName _To_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "to");
    private final static QName _TemplateLiteral_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "templateLiteral");
    private final static QName _Workflowdescription_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "workflowdescription");
    private final static QName _Operation_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "operation");
    private final static QName _Beanshellinput_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "beanshellinput");
    private final static QName _Inferno_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "inferno");
    private final static QName _Rshell_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "rshell");
    private final static QName _Beanshellinputlist_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "beanshellinputlist");
    private final static QName _Elements_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "elements");
    private final static QName _Service_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "service");
    private final static QName _Alternate_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "alternate");
    private final static QName _Cross_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "cross");
    private final static QName _ServiceName_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "serviceName");
    private final static QName _Slicelist_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "slicelist");
    private final static QName _Target_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "target");
    private final static QName _RshellOutputPort_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "rshellOutputPort");
    private final static QName _ArticleName_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "articleName");
    private final static QName _RshellInputPortList_QNAME = new QName("http://org.embl.ebi.escience/xscufl/0.1alpha", "rshellInputPortList");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.kit.scufl.other
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BeanshellType }
     * 
     */
    public BeanshellType createBeanshellType() {
        return new BeanshellType();
    }

    /**
     * Create an instance of {@link MetadataType }
     * 
     */
    public MetadataType createMetadataType() {
        return new MetadataType();
    }

    /**
     * Create an instance of {@link AuthorityNameType }
     * 
     */
    public AuthorityNameType createAuthorityNameType() {
        return new AuthorityNameType();
    }

    /**
     * Create an instance of {@link IterationstrategyType }
     * 
     */
    public IterationstrategyType createIterationstrategyType() {
        return new IterationstrategyType();
    }

    /**
     * Create an instance of {@link MimeTypeType }
     * 
     */
    public MimeTypeType createMimeTypeType() {
        return new MimeTypeType();
    }

    /**
     * Create an instance of {@link SourceType }
     * 
     */
    public SourceType createSourceType() {
        return new SourceType();
    }

    /**
     * Create an instance of {@link RepositoryType }
     * 
     */
    public RepositoryType createRepositoryType() {
        return new RepositoryType();
    }

    /**
     * Create an instance of {@link OutputPortListType }
     * 
     */
    public OutputPortListType createOutputPortListType() {
        return new OutputPortListType();
    }

    /**
     * Create an instance of {@link ArbitraryWsdlType }
     * 
     */
    public ArbitraryWsdlType createArbitraryWsdlType() {
        return new ArbitraryWsdlType();
    }

    /**
     * Create an instance of {@link CoordinationType }
     * 
     */
    public CoordinationType createCoordinationType() {
        return new CoordinationType();
    }

    /**
     * Create an instance of {@link ElementtypeType }
     * 
     */
    public ElementtypeType createElementtypeType() {
        return new ElementtypeType();
    }

    /**
     * Create an instance of {@link NodeType }
     * 
     */
    public NodeType createNodeType() {
        return new NodeType();
    }

    /**
     * Create an instance of {@link ArtifactType }
     * 
     */
    public ArtifactType createArtifactType() {
        return new ArtifactType();
    }

    /**
     * Create an instance of {@link NotificationType }
     * 
     */
    public NotificationType createNotificationType() {
        return new NotificationType();
    }

    /**
     * Create an instance of {@link IteratorType }
     * 
     */
    public IteratorType createIteratorType() {
        return new IteratorType();
    }

    /**
     * Create an instance of {@link MimeTypes }
     * 
     */
    public MimeTypes createMimeTypes() {
        return new MimeTypes();
    }

    /**
     * Create an instance of {@link ApiconsumerType }
     * 
     */
    public ApiconsumerType createApiconsumerType() {
        return new ApiconsumerType();
    }

    /**
     * Create an instance of {@link MapType }
     * 
     */
    public MapType createMapType() {
        return new MapType();
    }

    /**
     * Create an instance of {@link RepositoriesType }
     * 
     */
    public RepositoriesType createRepositoriesType() {
        return new RepositoriesType();
    }

    /**
     * Create an instance of {@link HostType }
     * 
     */
    public HostType createHostType() {
        return new HostType();
    }

    /**
     * Create an instance of {@link ActionType }
     * 
     */
    public ActionType createActionType() {
        return new ActionType();
    }

    /**
     * Create an instance of {@link StatusCodeType }
     * 
     */
    public StatusCodeType createStatusCodeType() {
        return new StatusCodeType();
    }

    /**
     * Create an instance of {@link ConditionStateType }
     * 
     */
    public ConditionStateType createConditionStateType() {
        return new ConditionStateType();
    }

    /**
     * Create an instance of {@link StringconstantType }
     * 
     */
    public StringconstantType createStringconstantType() {
        return new StringconstantType();
    }

    /**
     * Create an instance of {@link MethodType }
     * 
     */
    public MethodType createMethodType() {
        return new MethodType();
    }

    /**
     * Create an instance of {@link BiomobyobjectType }
     * 
     */
    public BiomobyobjectType createBiomobyobjectType() {
        return new BiomobyobjectType();
    }

    /**
     * Create an instance of {@link SinkType }
     * 
     */
    public SinkType createSinkType() {
        return new SinkType();
    }

    /**
     * Create an instance of {@link StatechangeType }
     * 
     */
    public StatechangeType createStatechangeType() {
        return new StatechangeType();
    }

    /**
     * Create an instance of {@link BeanshelloutputlistType }
     * 
     */
    public BeanshelloutputlistType createBeanshelloutputlistType() {
        return new BeanshelloutputlistType();
    }

    /**
     * Create an instance of {@link ScuflType }
     * 
     */
    public ScuflType createScuflType() {
        return new ScuflType();
    }

    /**
     * Create an instance of {@link ProcessorType }
     * 
     */
    public ProcessorType createProcessorType() {
        return new ProcessorType();
    }

    /**
     * Create an instance of {@link DependenciesType }
     * 
     */
    public DependenciesType createDependenciesType() {
        return new DependenciesType();
    }

    /**
     * Create an instance of {@link BiomobyparserType }
     * 
     */
    public BiomobyparserType createBiomobyparserType() {
        return new BiomobyparserType();
    }

    /**
     * Create an instance of {@link ConditionType }
     * 
     */
    public ConditionType createConditionType() {
        return new ConditionType();
    }

    /**
     * Create an instance of {@link OutputPortType }
     * 
     */
    public OutputPortType createOutputPortType() {
        return new OutputPortType();
    }

    /**
     * Create an instance of {@link ExtensionsType }
     * 
     */
    public ExtensionsType createExtensionsType() {
        return new ExtensionsType();
    }

    /**
     * Create an instance of {@link ArraytypeType }
     * 
     */
    public ArraytypeType createArraytypeType() {
        return new ArraytypeType();
    }

    /**
     * Create an instance of {@link DefaultsType }
     * 
     */
    public DefaultsType createDefaultsType() {
        return new DefaultsType();
    }

    /**
     * Create an instance of {@link PortType }
     * 
     */
    public PortType createPortType() {
        return new PortType();
    }

    /**
     * Create an instance of {@link SemanticTypeType }
     * 
     */
    public SemanticTypeType createSemanticTypeType() {
        return new SemanticTypeType();
    }

    /**
     * Create an instance of {@link TemplatePortReferenceType }
     * 
     */
    public TemplatePortReferenceType createTemplatePortReferenceType() {
        return new TemplatePortReferenceType();
    }

    /**
     * Create an instance of {@link BeanshelloutputType }
     * 
     */
    public BeanshelloutputType createBeanshelloutputType() {
        return new BeanshelloutputType();
    }

    /**
     * Create an instance of {@link TemplateType }
     * 
     */
    public TemplateType createTemplateType() {
        return new TemplateType();
    }

    /**
     * Create an instance of {@link BiomartType }
     * 
     */
    public BiomartType createBiomartType() {
        return new BiomartType();
    }

    /**
     * Create an instance of {@link RshellInputPortType }
     * 
     */
    public RshellInputPortType createRshellInputPortType() {
        return new RshellInputPortType();
    }

    /**
     * Create an instance of {@link BiomobywsdlType }
     * 
     */
    public BiomobywsdlType createBiomobywsdlType() {
        return new BiomobywsdlType();
    }

    /**
     * Create an instance of {@link JarfileType }
     * 
     */
    public JarfileType createJarfileType() {
        return new JarfileType();
    }

    /**
     * Create an instance of {@link DotType }
     * 
     */
    public DotType createDotType() {
        return new DotType();
    }

    /**
     * Create an instance of {@link LinkType }
     * 
     */
    public LinkType createLinkType() {
        return new LinkType();
    }

    /**
     * Create an instance of {@link DescriptionType }
     * 
     */
    public DescriptionType createDescriptionType() {
        return new DescriptionType();
    }

    /**
     * Create an instance of {@link MobyEndpointType }
     * 
     */
    public MobyEndpointType createMobyEndpointType() {
        return new MobyEndpointType();
    }

    /**
     * Create an instance of {@link RshellOutputPortListType }
     * 
     */
    public RshellOutputPortListType createRshellOutputPortListType() {
        return new RshellOutputPortListType();
    }

    /**
     * Create an instance of {@link LocalType }
     * 
     */
    public LocalType createLocalType() {
        return new LocalType();
    }

    /**
     * Create an instance of {@link SoaplabwsdlType }
     * 
     */
    public SoaplabwsdlType createSoaplabwsdlType() {
        return new SoaplabwsdlType();
    }

    /**
     * Create an instance of {@link DefaultType }
     * 
     */
    public DefaultType createDefaultType() {
        return new DefaultType();
    }

    /**
     * Create an instance of {@link EndpointType }
     * 
     */
    public EndpointType createEndpointType() {
        return new EndpointType();
    }

    /**
     * Create an instance of {@link WsdlType }
     * 
     */
    public WsdlType createWsdlType() {
        return new WsdlType();
    }

    /**
     * Create an instance of {@link AbstractprocessorType }
     * 
     */
    public AbstractprocessorType createAbstractprocessorType() {
        return new AbstractprocessorType();
    }

    /**
     * Create an instance of {@link DatatypeType }
     * 
     */
    public DatatypeType createDatatypeType() {
        return new DatatypeType();
    }

    /**
     * Create an instance of {@link ScriptvalueType }
     * 
     */
    public ScriptvalueType createScriptvalueType() {
        return new ScriptvalueType();
    }

    /**
     * Create an instance of {@link ComplextypeType }
     * 
     */
    public ComplextypeType createComplextypeType() {
        return new ComplextypeType();
    }

    /**
     * Create an instance of {@link InputPortType }
     * 
     */
    public InputPortType createInputPortType() {
        return new InputPortType();
    }

    /**
     * Create an instance of {@link ApiConsumerParameterType }
     * 
     */
    public ApiConsumerParameterType createApiConsumerParameterType() {
        return new ApiConsumerParameterType();
    }

    /**
     * Create an instance of {@link FlattenlistType }
     * 
     */
    public FlattenlistType createFlattenlistType() {
        return new FlattenlistType();
    }

    /**
     * Create an instance of {@link MergemodeType }
     * 
     */
    public MergemodeType createMergemodeType() {
        return new MergemodeType();
    }

    /**
     * Create an instance of {@link InputPortListType }
     * 
     */
    public InputPortListType createInputPortListType() {
        return new InputPortListType();
    }

    /**
     * Create an instance of {@link ClassType }
     * 
     */
    public ClassType createClassType() {
        return new ClassType();
    }

    /**
     * Create an instance of {@link RshellOutputPortType }
     * 
     */
    public RshellOutputPortType createRshellOutputPortType() {
        return new RshellOutputPortType();
    }

    /**
     * Create an instance of {@link ArticleNameType }
     * 
     */
    public ArticleNameType createArticleNameType() {
        return new ArticleNameType();
    }

    /**
     * Create an instance of {@link RshellInputPortListType }
     * 
     */
    public RshellInputPortListType createRshellInputPortListType() {
        return new RshellInputPortListType();
    }

    /**
     * Create an instance of {@link CrossType }
     * 
     */
    public CrossType createCrossType() {
        return new CrossType();
    }

    /**
     * Create an instance of {@link AlternateType }
     * 
     */
    public AlternateType createAlternateType() {
        return new AlternateType();
    }

    /**
     * Create an instance of {@link ServiceNameType }
     * 
     */
    public ServiceNameType createServiceNameType() {
        return new ServiceNameType();
    }

    /**
     * Create an instance of {@link SlicelistType }
     * 
     */
    public SlicelistType createSlicelistType() {
        return new SlicelistType();
    }

    /**
     * Create an instance of {@link TargetType }
     * 
     */
    public TargetType createTargetType() {
        return new TargetType();
    }

    /**
     * Create an instance of {@link RshellType }
     * 
     */
    public RshellType createRshellType() {
        return new RshellType();
    }

    /**
     * Create an instance of {@link BeanshellinputlistType }
     * 
     */
    public BeanshellinputlistType createBeanshellinputlistType() {
        return new BeanshellinputlistType();
    }

    /**
     * Create an instance of {@link ServiceType }
     * 
     */
    public ServiceType createServiceType() {
        return new ServiceType();
    }

    /**
     * Create an instance of {@link ElementsType }
     * 
     */
    public ElementsType createElementsType() {
        return new ElementsType();
    }

    /**
     * Create an instance of {@link BiomobyParameterType }
     * 
     */
    public BiomobyParameterType createBiomobyParameterType() {
        return new BiomobyParameterType();
    }

    /**
     * Create an instance of {@link BasetypeType }
     * 
     */
    public BasetypeType createBasetypeType() {
        return new BasetypeType();
    }

    /**
     * Create an instance of {@link TemplateLiteralType }
     * 
     */
    public TemplateLiteralType createTemplateLiteralType() {
        return new TemplateLiteralType();
    }

    /**
     * Create an instance of {@link WorkflowDescriptionType }
     * 
     */
    public WorkflowDescriptionType createWorkflowDescriptionType() {
        return new WorkflowDescriptionType();
    }

    /**
     * Create an instance of {@link BeanshellinputType }
     * 
     */
    public BeanshellinputType createBeanshellinputType() {
        return new BeanshellinputType();
    }

    /**
     * Create an instance of {@link OperationType }
     * 
     */
    public OperationType createOperationType() {
        return new OperationType();
    }

    /**
     * Create an instance of {@link InfernoType }
     * 
     */
    public InfernoType createInfernoType() {
        return new InfernoType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "action")
    public JAXBElement<ActionType> createAction(ActionType value) {
        return new JAXBElement<ActionType>(_Action_QNAME, ActionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HostType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "host")
    public JAXBElement<HostType> createHost(HostType value) {
        return new JAXBElement<HostType>(_Host_QNAME, HostType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConditionStateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "state")
    public JAXBElement<ConditionStateType> createState(ConditionStateType value) {
        return new JAXBElement<ConditionStateType>(_State_QNAME, ConditionStateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatusCodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "from")
    public JAXBElement<StatusCodeType> createFrom(StatusCodeType value) {
        return new JAXBElement<StatusCodeType>(_From_QNAME, StatusCodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StringconstantType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "stringconstant", substitutionHeadNamespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", substitutionHeadName = "processorElement")
    public JAXBElement<StringconstantType> createStringconstant(StringconstantType value) {
        return new JAXBElement<StringconstantType>(_Stringconstant_QNAME, StringconstantType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "notification", substitutionHeadNamespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", substitutionHeadName = "processorElement")
    public JAXBElement<NotificationType> createNotification(NotificationType value) {
        return new JAXBElement<NotificationType>(_Notification_QNAME, NotificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "output")
    public JAXBElement<NodeType> createOutput(NodeType value) {
        return new JAXBElement<NodeType>(_Output_QNAME, NodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArtifactType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "artifact")
    public JAXBElement<ArtifactType> createArtifact(ArtifactType value) {
        return new JAXBElement<ArtifactType>(_Artifact_QNAME, ArtifactType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ApiconsumerType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "apiconsumer", substitutionHeadNamespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", substitutionHeadName = "processorElement")
    public JAXBElement<ApiconsumerType> createApiconsumer(ApiconsumerType value) {
        return new JAXBElement<ApiconsumerType>(_Apiconsumer_QNAME, ApiconsumerType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IteratorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "iterator")
    public JAXBElement<IteratorType> createIterator(IteratorType value) {
        return new JAXBElement<IteratorType>(_Iterator_QNAME, IteratorType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MapType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "outputmap")
    public JAXBElement<MapType> createOutputmap(MapType value) {
        return new JAXBElement<MapType>(_Outputmap_QNAME, MapType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RepositoriesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "repositories")
    public JAXBElement<RepositoriesType> createRepositories(RepositoriesType value) {
        return new JAXBElement<RepositoriesType>(_Repositories_QNAME, RepositoriesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MimeTypeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "mimeType")
    public JAXBElement<MimeTypeType> createMimeType(MimeTypeType value) {
        return new JAXBElement<MimeTypeType>(_MimeType_QNAME, MimeTypeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SourceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "source")
    public JAXBElement<SourceType> createSource(SourceType value) {
        return new JAXBElement<SourceType>(_Source_QNAME, SourceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IterationstrategyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "iterationstrategy")
    public JAXBElement<IterationstrategyType> createIterationstrategy(IterationstrategyType value) {
        return new JAXBElement<IterationstrategyType>(_Iterationstrategy_QNAME, IterationstrategyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OutputPortListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "outputPortList")
    public JAXBElement<OutputPortListType> createOutputPortList(OutputPortListType value) {
        return new JAXBElement<OutputPortListType>(_OutputPortList_QNAME, OutputPortListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArbitraryWsdlType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "arbitrarywsdl", substitutionHeadNamespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", substitutionHeadName = "processorElement")
    public JAXBElement<ArbitraryWsdlType> createArbitrarywsdl(ArbitraryWsdlType value) {
        return new JAXBElement<ArbitraryWsdlType>(_Arbitrarywsdl_QNAME, ArbitraryWsdlType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RepositoryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "repository")
    public JAXBElement<RepositoryType> createRepository(RepositoryType value) {
        return new JAXBElement<RepositoryType>(_Repository_QNAME, RepositoryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CoordinationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "coordination")
    public JAXBElement<CoordinationType> createCoordination(CoordinationType value) {
        return new JAXBElement<CoordinationType>(_Coordination_QNAME, CoordinationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ElementtypeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "elementtype")
    public JAXBElement<ElementtypeType> createElementtype(ElementtypeType value) {
        return new JAXBElement<ElementtypeType>(_Elementtype_QNAME, ElementtypeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BeanshellType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "beanshell", substitutionHeadNamespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", substitutionHeadName = "processorElement")
    public JAXBElement<BeanshellType> createBeanshell(BeanshellType value) {
        return new JAXBElement<BeanshellType>(_Beanshell_QNAME, BeanshellType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthorityNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "authorityName")
    public JAXBElement<AuthorityNameType> createAuthorityName(AuthorityNameType value) {
        return new JAXBElement<AuthorityNameType>(_AuthorityName_QNAME, AuthorityNameType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MetadataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "metadata")
    public JAXBElement<MetadataType> createMetadata(MetadataType value) {
        return new JAXBElement<MetadataType>(_Metadata_QNAME, MetadataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BeanshelloutputType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "beanshelloutput")
    public JAXBElement<BeanshelloutputType> createBeanshelloutput(BeanshelloutputType value) {
        return new JAXBElement<BeanshelloutputType>(_Beanshelloutput_QNAME, BeanshelloutputType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "input")
    public JAXBElement<NodeType> createInput(NodeType value) {
        return new JAXBElement<NodeType>(_Input_QNAME, NodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "processorElement")
    public JAXBElement<Object> createProcessorElement(Object value) {
        return new JAXBElement<Object>(_ProcessorElement_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BiomobyparserType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "biomobyparser", substitutionHeadNamespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", substitutionHeadName = "processorElement")
    public JAXBElement<BiomobyparserType> createBiomobyparser(BiomobyparserType value) {
        return new JAXBElement<BiomobyparserType>(_Biomobyparser_QNAME, BiomobyparserType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArraytypeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "arraytype")
    public JAXBElement<ArraytypeType> createArraytype(ArraytypeType value) {
        return new JAXBElement<ArraytypeType>(_Arraytype_QNAME, ArraytypeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConditionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "condition")
    public JAXBElement<ConditionType> createCondition(ConditionType value) {
        return new JAXBElement<ConditionType>(_Condition_QNAME, ConditionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OutputPortType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "outputPort")
    public JAXBElement<OutputPortType> createOutputPort(OutputPortType value) {
        return new JAXBElement<OutputPortType>(_OutputPort_QNAME, OutputPortType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtensionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "extensions")
    public JAXBElement<ExtensionsType> createExtensions(ExtensionsType value) {
        return new JAXBElement<ExtensionsType>(_Extensions_QNAME, ExtensionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PortType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "port")
    public JAXBElement<PortType> createPort(PortType value) {
        return new JAXBElement<PortType>(_Port_QNAME, PortType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DefaultsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "defaults")
    public JAXBElement<DefaultsType> createDefaults(DefaultsType value) {
        return new JAXBElement<DefaultsType>(_Defaults_QNAME, DefaultsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SemanticTypeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "semanticType")
    public JAXBElement<SemanticTypeType> createSemanticType(SemanticTypeType value) {
        return new JAXBElement<SemanticTypeType>(_SemanticType_QNAME, SemanticTypeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TemplatePortReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "templatePortReference")
    public JAXBElement<TemplatePortReferenceType> createTemplatePortReference(TemplatePortReferenceType value) {
        return new JAXBElement<TemplatePortReferenceType>(_TemplatePortReference_QNAME, TemplatePortReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ScuflType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "scufl")
    public JAXBElement<ScuflType> createScufl(ScuflType value) {
        return new JAXBElement<ScuflType>(_Scufl_QNAME, ScuflType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProcessorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "processor")
    public JAXBElement<ProcessorType> createProcessor(ProcessorType value) {
        return new JAXBElement<ProcessorType>(_Processor_QNAME, ProcessorType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DependenciesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "dependencies")
    public JAXBElement<DependenciesType> createDependencies(DependenciesType value) {
        return new JAXBElement<DependenciesType>(_Dependencies_QNAME, DependenciesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BiomobyobjectType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "biomobyobject", substitutionHeadNamespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", substitutionHeadName = "processorElement")
    public JAXBElement<BiomobyobjectType> createBiomobyobject(BiomobyobjectType value) {
        return new JAXBElement<BiomobyobjectType>(_Biomobyobject_QNAME, BiomobyobjectType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MethodType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "method")
    public JAXBElement<MethodType> createMethod(MethodType value) {
        return new JAXBElement<MethodType>(_Method_QNAME, MethodType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatechangeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "statechange")
    public JAXBElement<StatechangeType> createStatechange(StatechangeType value) {
        return new JAXBElement<StatechangeType>(_Statechange_QNAME, StatechangeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BeanshelloutputlistType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "beanshelloutputlist")
    public JAXBElement<BeanshelloutputlistType> createBeanshelloutputlist(BeanshelloutputlistType value) {
        return new JAXBElement<BeanshelloutputlistType>(_Beanshelloutputlist_QNAME, BeanshelloutputlistType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SinkType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "sink")
    public JAXBElement<SinkType> createSink(SinkType value) {
        return new JAXBElement<SinkType>(_Sink_QNAME, SinkType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MergemodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "mergemode")
    public JAXBElement<MergemodeType> createMergemode(MergemodeType value) {
        return new JAXBElement<MergemodeType>(_Mergemode_QNAME, MergemodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InputPortListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "inputPortList")
    public JAXBElement<InputPortListType> createInputPortList(InputPortListType value) {
        return new JAXBElement<InputPortListType>(_InputPortList_QNAME, InputPortListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClassType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "class")
    public JAXBElement<ClassType> createClass(ClassType value) {
        return new JAXBElement<ClassType>(_Class_QNAME, ClassType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MapType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "inputmap")
    public JAXBElement<MapType> createInputmap(MapType value) {
        return new JAXBElement<MapType>(_Inputmap_QNAME, MapType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FlattenlistType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "flattenlist")
    public JAXBElement<FlattenlistType> createFlattenlist(FlattenlistType value) {
        return new JAXBElement<FlattenlistType>(_Flattenlist_QNAME, FlattenlistType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WsdlType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "wsdl")
    public JAXBElement<WsdlType> createWsdl(WsdlType value) {
        return new JAXBElement<WsdlType>(_Wsdl_QNAME, WsdlType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DefaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "default")
    public JAXBElement<DefaultType> createDefault(DefaultType value) {
        return new JAXBElement<DefaultType>(_Default_QNAME, DefaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EndpointType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "endpoint")
    public JAXBElement<EndpointType> createEndpoint(EndpointType value) {
        return new JAXBElement<EndpointType>(_Endpoint_QNAME, EndpointType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DatatypeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "datatype")
    public JAXBElement<DatatypeType> createDatatype(DatatypeType value) {
        return new JAXBElement<DatatypeType>(_Datatype_QNAME, DatatypeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractprocessorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "abstractprocessor", substitutionHeadNamespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", substitutionHeadName = "processorElement")
    public JAXBElement<AbstractprocessorType> createAbstractprocessor(AbstractprocessorType value) {
        return new JAXBElement<AbstractprocessorType>(_Abstractprocessor_QNAME, AbstractprocessorType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InputPortType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "inputPort")
    public JAXBElement<InputPortType> createInputPort(InputPortType value) {
        return new JAXBElement<InputPortType>(_InputPort_QNAME, InputPortType.class, null, value);
    }

    /**
     * Create an instance of {@link ApiConsumerParameter }}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "parameter")
    public ApiConsumerParameter createApiConsumerParameter(ApiConsumerParameterType value) {
        return new ApiConsumerParameter(value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ScriptvalueType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "scriptvalue")
    public JAXBElement<ScriptvalueType> createScriptvalue(ScriptvalueType value) {
        return new JAXBElement<ScriptvalueType>(_Scriptvalue_QNAME, ScriptvalueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ComplextypeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "complextype")
    public JAXBElement<ComplextypeType> createComplextype(ComplextypeType value) {
        return new JAXBElement<ComplextypeType>(_Complextype_QNAME, ComplextypeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DescriptionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "description")
    public JAXBElement<DescriptionType> createDescription(DescriptionType value) {
        return new JAXBElement<DescriptionType>(_Description_QNAME, DescriptionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DotType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "dot")
    public JAXBElement<DotType> createDot(DotType value) {
        return new JAXBElement<DotType>(_Dot_QNAME, DotType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LinkType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "link")
    public JAXBElement<LinkType> createLink(LinkType value) {
        return new JAXBElement<LinkType>(_Link_QNAME, LinkType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MobyEndpointType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "mobyEndpoint")
    public JAXBElement<MobyEndpointType> createMobyEndpoint(MobyEndpointType value) {
        return new JAXBElement<MobyEndpointType>(_MobyEndpoint_QNAME, MobyEndpointType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RshellOutputPortListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "rshellOutputPortList")
    public JAXBElement<RshellOutputPortListType> createRshellOutputPortList(RshellOutputPortListType value) {
        return new JAXBElement<RshellOutputPortListType>(_RshellOutputPortList_QNAME, RshellOutputPortListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SoaplabwsdlType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "soaplabwsdl", substitutionHeadNamespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", substitutionHeadName = "processorElement")
    public JAXBElement<SoaplabwsdlType> createSoaplabwsdl(SoaplabwsdlType value) {
        return new JAXBElement<SoaplabwsdlType>(_Soaplabwsdl_QNAME, SoaplabwsdlType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LocalType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "local", substitutionHeadNamespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", substitutionHeadName = "processorElement")
    public JAXBElement<LocalType> createLocal(LocalType value) {
        return new JAXBElement<LocalType>(_Local_QNAME, LocalType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TemplateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "template")
    public JAXBElement<TemplateType> createTemplate(TemplateType value) {
        return new JAXBElement<TemplateType>(_Template_QNAME, TemplateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BiomartType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "biomart", substitutionHeadNamespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", substitutionHeadName = "processorElement")
    public JAXBElement<BiomartType> createBiomart(BiomartType value) {
        return new JAXBElement<BiomartType>(_Biomart_QNAME, BiomartType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RshellInputPortType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "rshellInputPort")
    public JAXBElement<RshellInputPortType> createRshellInputPort(RshellInputPortType value) {
        return new JAXBElement<RshellInputPortType>(_RshellInputPort_QNAME, RshellInputPortType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BiomobywsdlType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "biomobywsdl", substitutionHeadNamespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", substitutionHeadName = "processorElement")
    public JAXBElement<BiomobywsdlType> createBiomobywsdl(BiomobywsdlType value) {
        return new JAXBElement<BiomobywsdlType>(_Biomobywsdl_QNAME, BiomobywsdlType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JarfileType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "jarfile")
    public JAXBElement<JarfileType> createJarfile(JarfileType value) {
        return new JAXBElement<JarfileType>(_Jarfile_QNAME, JarfileType.class, null, value);
    }

    /**
     * Create an instance of {@link BiomobyParameter }}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "Parameter")
    public BiomobyParameter createBiomobyParameter(BiomobyParameterType value) {
        return new BiomobyParameter(value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BasetypeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "basetype")
    public JAXBElement<BasetypeType> createBasetype(BasetypeType value) {
        return new JAXBElement<BasetypeType>(_Basetype_QNAME, BasetypeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatusCodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "to")
    public JAXBElement<StatusCodeType> createTo(StatusCodeType value) {
        return new JAXBElement<StatusCodeType>(_To_QNAME, StatusCodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TemplateLiteralType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "templateLiteral")
    public JAXBElement<TemplateLiteralType> createTemplateLiteral(TemplateLiteralType value) {
        return new JAXBElement<TemplateLiteralType>(_TemplateLiteral_QNAME, TemplateLiteralType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WorkflowDescriptionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "workflowdescription")
    public JAXBElement<WorkflowDescriptionType> createWorkflowdescription(WorkflowDescriptionType value) {
        return new JAXBElement<WorkflowDescriptionType>(_Workflowdescription_QNAME, WorkflowDescriptionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OperationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "operation")
    public JAXBElement<OperationType> createOperation(OperationType value) {
        return new JAXBElement<OperationType>(_Operation_QNAME, OperationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BeanshellinputType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "beanshellinput")
    public JAXBElement<BeanshellinputType> createBeanshellinput(BeanshellinputType value) {
        return new JAXBElement<BeanshellinputType>(_Beanshellinput_QNAME, BeanshellinputType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InfernoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "inferno", substitutionHeadNamespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", substitutionHeadName = "processorElement")
    public JAXBElement<InfernoType> createInferno(InfernoType value) {
        return new JAXBElement<InfernoType>(_Inferno_QNAME, InfernoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RshellType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "rshell", substitutionHeadNamespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", substitutionHeadName = "processorElement")
    public JAXBElement<RshellType> createRshell(RshellType value) {
        return new JAXBElement<RshellType>(_Rshell_QNAME, RshellType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BeanshellinputlistType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "beanshellinputlist")
    public JAXBElement<BeanshellinputlistType> createBeanshellinputlist(BeanshellinputlistType value) {
        return new JAXBElement<BeanshellinputlistType>(_Beanshellinputlist_QNAME, BeanshellinputlistType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ElementsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "elements")
    public JAXBElement<ElementsType> createElements(ElementsType value) {
        return new JAXBElement<ElementsType>(_Elements_QNAME, ElementsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "service")
    public JAXBElement<ServiceType> createService(ServiceType value) {
        return new JAXBElement<ServiceType>(_Service_QNAME, ServiceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AlternateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "alternate")
    public JAXBElement<AlternateType> createAlternate(AlternateType value) {
        return new JAXBElement<AlternateType>(_Alternate_QNAME, AlternateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CrossType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "cross")
    public JAXBElement<CrossType> createCross(CrossType value) {
        return new JAXBElement<CrossType>(_Cross_QNAME, CrossType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "serviceName")
    public JAXBElement<ServiceNameType> createServiceName(ServiceNameType value) {
        return new JAXBElement<ServiceNameType>(_ServiceName_QNAME, ServiceNameType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SlicelistType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "slicelist")
    public JAXBElement<SlicelistType> createSlicelist(SlicelistType value) {
        return new JAXBElement<SlicelistType>(_Slicelist_QNAME, SlicelistType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TargetType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "target")
    public JAXBElement<TargetType> createTarget(TargetType value) {
        return new JAXBElement<TargetType>(_Target_QNAME, TargetType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RshellOutputPortType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "rshellOutputPort")
    public JAXBElement<RshellOutputPortType> createRshellOutputPort(RshellOutputPortType value) {
        return new JAXBElement<RshellOutputPortType>(_RshellOutputPort_QNAME, RshellOutputPortType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArticleNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "articleName")
    public JAXBElement<ArticleNameType> createArticleName(ArticleNameType value) {
        return new JAXBElement<ArticleNameType>(_ArticleName_QNAME, ArticleNameType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RshellInputPortListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.embl.ebi.escience/xscufl/0.1alpha", name = "rshellInputPortList")
    public JAXBElement<RshellInputPortListType> createRshellInputPortList(RshellInputPortListType value) {
        return new JAXBElement<RshellInputPortListType>(_RshellInputPortList_QNAME, RshellInputPortListType.class, null, value);
    }

}
