//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 09:01:34 PM CET 
//


package org.kit.scufl.embl;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for scuflType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="scuflType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://org.embl.ebi.escience/xscufl/0.1alpha}workflowdescription"/>
 *         &lt;element ref="{http://org.embl.ebi.escience/xscufl/0.1alpha}processor" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://org.embl.ebi.escience/xscufl/0.1alpha}link" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://org.embl.ebi.escience/xscufl/0.1alpha}source" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://org.embl.ebi.escience/xscufl/0.1alpha}sink" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://org.embl.ebi.escience/xscufl/0.1alpha}coordination" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="log" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "scuflType", propOrder = {
    "workflowdescription",
    "processor",
    "link",
    "source",
    "sink",
    "coordination"
})
public class ScuflType {

    @XmlElement(required = true)
    protected WorkflowDescriptionType workflowdescription;
    protected List<ProcessorType> processor;
    protected List<LinkType> link;
    protected List<SourceType> source;
    protected List<SinkType> sink;
    protected List<CoordinationType> coordination;
    @XmlAttribute(name = "version")
    protected String version;
    @XmlAttribute(name = "log")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger log;

    /**
     * Gets the value of the workflowdescription property.
     * 
     * @return
     *     possible object is
     *     {@link WorkflowDescriptionType }
     *     
     */
    public WorkflowDescriptionType getWorkflowdescription() {
        return workflowdescription;
    }

    /**
     * Sets the value of the workflowdescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkflowDescriptionType }
     *     
     */
    public void setWorkflowdescription(WorkflowDescriptionType value) {
        this.workflowdescription = value;
    }

    /**
     * Gets the value of the processor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the processor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProcessor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProcessorType }
     * 
     * 
     */
    public List<ProcessorType> getProcessor() {
        if (processor == null) {
            processor = new ArrayList<ProcessorType>();
        }
        return this.processor;
    }

    /**
     * Gets the value of the link property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the link property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLink().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LinkType }
     * 
     * 
     */
    public List<LinkType> getLink() {
        if (link == null) {
            link = new ArrayList<LinkType>();
        }
        return this.link;
    }

    /**
     * Gets the value of the source property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the source property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SourceType }
     * 
     * 
     */
    public List<SourceType> getSource() {
        if (source == null) {
            source = new ArrayList<SourceType>();
        }
        return this.source;
    }

    /**
     * Gets the value of the sink property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sink property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSink().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SinkType }
     * 
     * 
     */
    public List<SinkType> getSink() {
        if (sink == null) {
            sink = new ArrayList<SinkType>();
        }
        return this.sink;
    }

    /**
     * Gets the value of the coordination property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the coordination property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCoordination().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CoordinationType }
     * 
     * 
     */
    public List<CoordinationType> getCoordination() {
        if (coordination == null) {
            coordination = new ArrayList<CoordinationType>();
        }
        return this.coordination;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the log property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLog() {
        return log;
    }

    /**
     * Sets the value of the log property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLog(BigInteger value) {
        this.log = value;
    }

}
